// Bundles the BOOT strings — and only those — into the web shell.
//
// Every other string in this app comes from the engine, in one call, the way
// core/src/i18n.rs describes. The splash cannot wait for that: it paints in the
// first frame and the engine binary is still downloading, so on a cold visit a
// German reader would read English for a second or two, and a boot that FAILED
// would leave them reading English forever. These few keys therefore ride in
// the JS bundle.
//
// Generated, not hand-copied, from the same crates/core/src/i18n/*.json the
// engine compiles in — one source, and a stale copy is impossible because this
// runs before every build and check.
//
// The prefix filter is what keeps the cost honest: the whole catalogue is tens
// of KB per language and will grow, while this is a couple of hundred bytes and
// is bounded by the number of things a splash can say.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "../../../crates/core/src/i18n");
const out = join(here, "../src/lib/i18n.generated.ts");

/** Keys the shell may need before the engine has answered anything. */
const PREFIX = "boot.";

const langs = readdirSync(src)
  .filter((f) => f.endsWith(".json"))
  .map((f) => f.slice(0, -5))
  .sort();

const picked = {};
for (const lang of langs) {
  const all = JSON.parse(readFileSync(join(src, `${lang}.json`), "utf8"));
  const mine = {};
  for (const k of Object.keys(all).sort()) if (k.startsWith(PREFIX)) mine[k] = all[k];
  picked[lang] = mine;
}

// English is the source, so a key it lacks cannot exist; a key another language
// lacks is a gap the runtime fills by laying it over English (see i18n.svelte.ts).
if (Object.keys(picked.en ?? {}).length === 0) {
  throw new Error(`no ${PREFIX}* keys in ${src}/en.json — the splash would have nothing to say`);
}

const body = Object.entries(picked)
  .map(([lang, strings]) => `  ${lang}: ${JSON.stringify(strings, null, 2).replace(/\n/g, "\n  ")},`)
  .join("\n");

writeFileSync(
  out,
  `// GENERATED by scripts/gen-i18n.mjs from crates/core/src/i18n/*.json — do not edit.
//
// The ${PREFIX}* keys only: what the splash and the boot-failure screen say,
// which is everything the shell must be able to paint before the engine exists.
// The rest of the catalogue arrives on the boot reply.

export const BOOT_STRINGS: Record<string, Record<string, string>> = {
${body}
};
`,
);

console.log(`i18n: ${langs.length} languages × ${Object.keys(picked.en).length} boot keys → src/lib/i18n.generated.ts`);
