// GENERATED by scripts/subset-fonts.mjs — do not edit.
//
// Every bundled family, keyed by its `core::font::Font` token. The engine
// worker loads the SELECTED family's files into its own FontFaceSet to MEASURE
// layout; public/fonts.css declares the same files for the document to PAINT
// with. Same bytes in both, which is what keeps measured line breaks and
// painted line breaks identical.

/** A family's woff2 paths, relative to the app base. `italic` is absent for a
 *  face that ships none — see `core::font::Font::has_italic`. */
export type FontFiles = { readonly normal: string; readonly italic?: string };

export const FONT_FILES: Readonly<Record<string, FontFiles>> = {
  "eb-garamond": { normal: "fonts/EBGaramond-12d2a64e.woff2", italic: "fonts/EBGaramond-Italic-74dbff24.woff2" },
  "literata": { normal: "fonts/Literata-4d7dcb71.woff2", italic: "fonts/Literata-Italic-d38ec0f7.woff2" },
  "inter": { normal: "fonts/Inter-8366ba8a.woff2", italic: "fonts/Inter-Italic-46b982a6.woff2" },
  "fira-code": { normal: "fonts/FiraCode-909ef859.woff2" },
  "atkinson-hyperlegible": { normal: "fonts/AtkinsonHyperlegible-Regular-4327a45b.woff2", italic: "fonts/AtkinsonHyperlegible-Italic-e0777042.woff2" },
  "amiri": { normal: "fonts/Amiri-Regular-cf168c16.woff2" },
};

/** Token → the family name the @font-face rules declare (what a `ctx.font`
 *  string or a CSS `font-family` must name to get this face). */
export const FONT_CSS_FAMILY: Readonly<Record<string, string>> = {
  "eb-garamond": "EB Garamond",
  "literata": "Literata",
  "inter": "Inter",
  "fira-code": "Fira Code",
  "atkinson-hyperlegible": "Atkinson Hyperlegible",
  "amiri": "Amiri",
};

/** The face every axis falls back to — the shipped default, and the answer for
 *  a token this build does not know (a config written by a later build). */
export const DEFAULT_FONT = "eb-garamond";

/** Token → what to render in until the webfont lands, and for any codepoint the
 *  family lacks. A sans must not fall back to a serif: the substitution shows
 *  for one swap, and on a glyph the face is missing it is permanent. */
 *
 *  Every other stack opens with "Amiri", which is not a choice and not in the
 *  picker: none of the selectable faces has a single Arabic glyph, and per-glyph
 *  fallback is what lets one stack serve Latin in the reader's chosen voice and
 *  Arabic in a face that can actually shape it. It sits FIRST among the
 *  fallbacks and after the chosen family, so it only ever answers for codepoints
 *  the chosen family lacks. */
export const FONT_FALLBACK: Readonly<Record<string, string>> = {
  "eb-garamond": "\"Amiri\", Georgia, serif",
  "literata": "\"Amiri\", Georgia, serif",
  "inter": "\"Amiri\", system-ui, sans-serif",
  "fira-code": "\"Amiri\", ui-monospace, monospace",
  "atkinson-hyperlegible": "\"Amiri\", system-ui, sans-serif",
  "amiri": "serif",
};

/** The script-fallback face, loaded by the engine worker ALONGSIDE whichever
 *  family is selected and declared in fonts.css for the document.
 *
 *  Unconditional on purpose. It could be loaded only when the open corpus reads
 *  right to left, but then the worker's font set would depend on which Bible is
 *  open, and the window where the two contexts disagree is exactly the window
 *  where a reader switches language. One face, always present in both. */
export const SCRIPT_FALLBACK_FILES: readonly string[] = ["fonts/Amiri-Regular-cf168c16.woff2"];

/** Token → the face's optical size multiplier, mirroring
 *  `core::font::Font::scale()` (which holds the x-height measurements and the
 *  half-correction rationale). Applied at render time by reader/measure.ts's
 *  `readerFontPx` and composed into `--uiScale` for the chrome — NEVER
 *  written into `config.bodySize`. */
export const FONT_SCALE: Readonly<Record<string, number>> = {
  "eb-garamond": 1,
  "literata": 0.89,
  "inter": 0.87,
  "fira-code": 0.88,
  "atkinson-hyperlegible": 0.9,
  "amiri": 1.06,
};

/** EVERY built font file — FONT_FILES plus the chrome-only static bolds that
 *  the engine worker never measures with. This is the offline PRECACHE list
 *  (vite.config's shell manifest): a face the document can be asked to paint
 *  must be on the device, or "can I read offline" depends on whether bold
 *  chrome text ever rendered while the network was up. */
export const FONT_ALL_FILES: readonly string[] = [
  "fonts/EBGaramond-12d2a64e.woff2",
  "fonts/EBGaramond-Italic-74dbff24.woff2",
  "fonts/Literata-4d7dcb71.woff2",
  "fonts/Literata-Italic-d38ec0f7.woff2",
  "fonts/Inter-8366ba8a.woff2",
  "fonts/Inter-Italic-46b982a6.woff2",
  "fonts/FiraCode-909ef859.woff2",
  "fonts/AtkinsonHyperlegible-Regular-4327a45b.woff2",
  "fonts/AtkinsonHyperlegible-Italic-e0777042.woff2",
  "fonts/AtkinsonHyperlegible-Bold-d14a069b.woff2",
  "fonts/AtkinsonHyperlegible-BoldItalic-26c11fe2.woff2",
  "fonts/Amiri-Regular-cf168c16.woff2",
];
