// GENERATED by scripts/subset-fonts.mjs — do not edit.
//
// The reader face, as paths relative to the app base. The engine worker loads
// these into its own FontFaceSet to MEASURE layout; public/fonts.css declares
// the same files for the document to PAINT with. Same bytes in both, which is
// what keeps measured line breaks and painted line breaks identical.
export const READER_FONT_FILES = {
  normal: "fonts/EBGaramond-12d2a64e.woff2",
  italic: "fonts/EBGaramond-Italic-74dbff24.woff2",
} as const;

/** Both faces, for preloading and for the offline shell list. */
export const READER_FONT_PATHS: readonly string[] = Object.values(READER_FONT_FILES);
