// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace PureStudy.Native
{
    public static unsafe partial class PureStudyNative
    {
        const string __DllName = "pure_ffi";





        /// <summary>
        ///  The pure-study core version as a caller-freed NUL-terminated UTF-8 string.
        ///  Never null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_study_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_study_version();

        /// <summary>
        ///  Free a string previously returned by any `pure_*` function. Null is a no-op.
        ///
        ///  # Safety
        ///  `ptr` must be a pointer returned by this library and not already freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_study_string_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void pure_study_string_free(byte* ptr);

        /// <summary>
        ///  Open an engine from an overlay-style home directory containing
        ///  `data/kjv.jsonl` and `data/strongs.json`.
        ///
        ///  Returns null on failure; if `out_err` is non-null it receives a caller-freed
        ///  error message (and is set to null on success).
        ///
        ///  # Safety
        ///  `home` is a valid NUL-terminated UTF-8 path; `out_err` is null or a writable
        ///  slot for one `*mut c_char`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_open", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern PureEngine* pure_engine_open(byte* home, byte** out_err);

        /// <summary>
        ///  Open an engine from in-memory bytes — for shells that bundle the data as
        ///  assets/resources (decision #3): the `kjv.jsonl` text and the `strongs.json`
        ///  object, each as a length-delimited byte buffer (need not be NUL-terminated).
        ///
        ///  Returns null on failure; `out_err` behaves as in [`pure_engine_open`].
        ///
        ///  # Safety
        ///  Each `*_ptr`/`*_len` pair describes a readable buffer of that length (a null
        ///  pointer with length 0 is treated as empty and will error); `out_err` is null
        ///  or a writable slot.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_open_from_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern PureEngine* pure_engine_open_from_bytes(byte* kjv_ptr, nuint kjv_len, byte* strongs_ptr, nuint strongs_len, byte** out_err);

        /// <summary>
        ///  Release an engine. Null is a no-op.
        ///
        ///  # Safety
        ///  `engine` must be a pointer from `pure_engine_open*` and not already freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void pure_engine_free(PureEngine* engine);

        /// <summary>
        ///  Table of contents as JSON: `{"books":[{"id","name","chapters"},...]}` in
        ///  canonical order. Chapter counts reflect the loaded corpus and are floored at
        ///  1 for any book the corpus lacks (the full KJV corpus has all 66 books, so in
        ///  production the counts are exact). Caller-freed; null only on a null engine.
        ///
        ///  # Safety
        ///  `engine` is a valid engine pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_toc_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_toc_json(PureEngine* engine);

        /// <summary>
        ///  Number of chapters the loaded corpus has for `book` (an OSIS id like
        ///  `"John"`). Floored at 1 for a book the corpus lacks (a safe UI range floor);
        ///  0 only on a null engine.
        ///
        ///  # Safety
        ///  `engine` is valid; `book` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_chapter_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint pure_engine_chapter_count(PureEngine* engine, byte* book);

        /// <summary>
        ///  A single verse as JSON:
        ///  `{"reference","display","body","title","tokens":[...]}`. `reference` is a
        ///  compact key like `"John 3:16"`. Null if the reference is unknown or
        ///  unparseable. Caller-freed.
        ///
        ///  # Safety
        ///  `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_verse_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_verse_json(PureEngine* engine, byte* ref_key);

        /// <summary>
        ///  A single token as JSON: `{"pre","word","post","render","flags","strongs"}`.
        ///  Null if the reference or token index is out of range. Caller-freed.
        ///
        ///  # Safety
        ///  `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_token_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_token_json(PureEngine* engine, byte* ref_key, uint token_index);

        /// <summary>
        ///  Lay out a chapter into a display list, measuring text through `measure`
        ///  (called with `measure_ctx`). Returns an opaque handle to release with
        ///  [`pure_layout_free`], or null on a null engine, a null callback, or an
        ///  unknown/out-of-range book+chapter (no such verses). Because the KJV has no
        ///  empty chapters, a null return reliably means "past the end" — a shell can
        ///  page by advancing until it gets null.
        ///
        ///  # Safety
        ///  `engine` is valid; `book` is a valid NUL-terminated UTF-8 string; `measure`
        ///  is a valid function pointer for the call and `measure_ctx` is whatever it
        ///  expects (it is passed back verbatim).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_layout_chapter", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern PureDisplayList* pure_engine_layout_chapter(PureEngine* engine, byte* book, uint chapter, PureLayoutConfig cfg, delegate* unmanaged[Cdecl]<void*, byte*, float> measure, void* measure_ctx);

        /// <summary>
        ///  The full display list as JSON (see [`wire`] for the schema): positioned
        ///  items plus the total painted `width`/`height`. Caller-freed; null on a null
        ///  handle.
        ///
        ///  # Safety
        ///  `dl` is a valid display-list pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_layout_to_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_layout_to_json(PureDisplayList* dl);

        /// <summary>
        ///  Total painted height in device pixels (scrollbar extent). 0 on a null handle.
        ///
        ///  # Safety
        ///  `dl` is a valid display-list pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_layout_height", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float pure_layout_height(PureDisplayList* dl);

        /// <summary>
        ///  The column width the layout targeted. 0 on a null handle.
        ///
        ///  # Safety
        ///  `dl` is a valid display-list pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_layout_width", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float pure_layout_width(PureDisplayList* dl);

        /// <summary>
        ///  Number of placed items in the display list. 0 on a null handle.
        ///
        ///  # Safety
        ///  `dl` is a valid display-list pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_layout_item_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint pure_layout_item_count(PureDisplayList* dl);

        /// <summary>
        ///  Resolve a point (in the display list's own coordinate space) to the word
        ///  under it. Returns a `Hit` JSON (`{"verse","display","tokenIndex","strongs"}`)
        ///  or null when the point hits a verse number, a gap, or nothing. Caller-freed.
        ///
        ///  # Safety
        ///  `dl` is a valid display-list pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_layout_hit_test_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_layout_hit_test_json(PureDisplayList* dl, float x, float y);

        /// <summary>
        ///  Release a display list. Null is a no-op.
        ///
        ///  # Safety
        ///  `dl` must be a pointer from [`pure_engine_layout_chapter`] and not already
        ///  freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_layout_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void pure_layout_free(PureDisplayList* dl);

        /// <summary>
        ///  A Strong's entry as JSON: `{"code","lemma","xlit","pron","deriv","def",
        ///  "kjv"}` (unknown fields null). Null when the code is absent. Caller-freed.
        ///
        ///  # Safety
        ///  `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_strongs_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_strongs_json(PureEngine* engine, byte* code);

        /// <summary>
        ///  The concordance for a Strong's code as JSON: `{"code","total","capped",
        ///  "verses":["Gen 1:1",...]}`. `verses` is capped at [`OCCURRENCE_CAP`] in
        ///  canonical order; `total` is the honest count and `capped` says whether the
        ///  list was truncated. Caller-freed; null on a null engine.
        ///
        ///  # Safety
        ///  `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_strongs_occurrences_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_strongs_occurrences_json(PureEngine* engine, byte* code);

        /// <summary>
        ///  The rendering lens for a Strong's code: every distinct English rendering of
        ///  it, most frequent first, each with an occurrence count and its (capped)
        ///  verse refs + token spans. `{"code","renderings":[{"rendering","total",
        ///  "capped","refs":[{"verse","display","span":[start,end]}]}]}`. Each `refs`
        ///  list is capped at [`OCCURRENCE_CAP`]; `renderings` is empty for an untagged
        ///  or unknown code. Null only on a null engine. Caller-freed.
        ///
        ///  # Safety
        ///  `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_renderings_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_renderings_json(PureEngine* engine, byte* code);

        /// <summary>
        ///  The reverse lens: the Strong's codes a surface English word translates,
        ///  most frequent first. `{"word","codes":[{"code","count"}]}`. Reveals where
        ///  one English word hides a Greek/Hebrew distinction ("love" ← agape and
        ///  phileo); `codes` is empty for an untagged word. Null only on a null engine.
        ///  Caller-freed.
        ///
        ///  # Safety
        ///  `engine` is valid; `word` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_word_codes_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_word_codes_json(PureEngine* engine, byte* word);

        /// <summary>
        ///  Run a query through the multi-tier search and return a `SearchAnswer` JSON:
        ///  either `{"kind":"goto",...}` (the query was a reference) or
        ///  `{"kind":"hits","how","total","capped","hits":[...]}`. Null when the query is
        ///  blank or the engine is null. Caller-freed.
        ///
        ///  # Safety
        ///  `engine` is valid; `query` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_search_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_search_json(PureEngine* engine, byte* query);

        /// <summary>
        ///  The loaded threads as JSON: `{"threads":[{name,notes,created,entries:[…]}]}`.
        ///  Caller-freed; null on a null engine.
        ///
        ///  # Safety
        ///  `engine` is a valid engine pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_threads_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_threads_json(PureEngine* engine);

        /// <summary>
        ///  The loaded tags as JSON: `{"tags":[{name,color,created,members:[…]}]}`.
        ///  Caller-freed; null on a null engine.
        ///
        ///  # Safety
        ///  `engine` is a valid engine pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_tags_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_tags_json(PureEngine* engine);

        /// <summary>
        ///  A verse's weave cross-reference partners as JSON:
        ///  `{"verse","partners":[{"verse","display","weave"}]}`. Caller-freed; null on a
        ///  null engine or an unparseable reference.
        ///
        ///  # Safety
        ///  `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_verse_xrefs_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_verse_xrefs_json(PureEngine* engine, byte* ref_key);

        /// <summary>
        ///  The suggested weaves (proposals under `home/weaves/suggested`) awaiting
        ///  review, as JSON: `{"suggested":[{index,name,kind,notes,links:[…]}]}`. Each
        ///  item's `index` is the ordinal within the suggested subset — the handle the
        ///  approve/reject calls take. Caller-freed; null on a null engine.
        ///
        ///  # Safety
        ///  `engine` is a valid engine pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_suggested_weaves_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_suggested_weaves_json(PureEngine* engine);

        /// <summary>
        ///  Concept neighbours of a Strong's code as JSON:
        ///  `{"code","near":[{code,score}],"cross":[{code,score}]}` (same-testament, then
        ///  cross-testament — the latter empty unless the embedding is aligned). Null
        ///  when no embedding is loaded or the args are invalid.
        ///
        ///  # Safety
        ///  `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_concept_neighbours_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_concept_neighbours_json(PureEngine* engine, byte* code, uint k);

        /// <summary>
        ///  The fused OT↔NT bridge partners of a Strong's code as JSON:
        ///  `{"code","partners":[{code,sources,prior}]}`, ranked by trust prior. The
        ///  etymology layer works from the dictionary alone, so this is available even
        ///  for a bytes-opened engine (external witnesses need a home). Null on a null
        ///  engine / invalid code.
        ///
        ///  # Safety
        ///  `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_bridge_partners_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_bridge_partners_json(PureEngine* engine, byte* code);

        /// <summary>
        ///  The morphology of one token as JSON:
        ///  `{"verse","tokenIndex","code","gloss"}`. Null when no morphology is loaded,
        ///  the reference is unparseable, or that token carries no annotation.
        ///
        ///  # Safety
        ///  `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_morph_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_morph_json(PureEngine* engine, byte* ref_key, uint token_index);

        /// <summary>
        ///  "Verses like this one" (SIF) as JSON:
        ///  `{"verse","in":[{verse,display,score}],"cross":[…]}`. The SIF model is built
        ///  lazily on the first call (heavy) and cached. Null when no embedding is
        ///  loaded or the reference is unparseable.
        ///
        ///  # Safety
        ///  `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_similar_verses_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_similar_verses_json(PureEngine* engine, byte* ref_key, uint k);

        /// <summary>
        ///  Add the whole verse `ref_key` to the thread named `name` (created on first
        ///  use). `note` may be null; `added` is a caller-supplied UTC timestamp.
        ///
        ///  # Safety
        ///  `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_thread_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_thread_add(PureEngine* engine, byte* name, byte* ref_key, byte* note, byte* added);

        /// <summary>
        ///  Add a target to the tag named `name` (created on first use). `kind` is
        ///  `"verse"` (with `value` a ref key) or `"concept"` (with `value` a Strong's
        ///  code). `note` may be null; `added` is a caller-supplied UTC timestamp.
        ///
        ///  # Safety
        ///  `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_tag_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_tag_add(PureEngine* engine, byte* name, byte* kind, byte* value, byte* note, byte* added);

        /// <summary>
        ///  Remove a target (see [`pure_engine_tag_add`] for `kind`/`value`) from the tag
        ///  named `name`. A missing target is a no-op; a missing tag is an error.
        ///
        ///  # Safety
        ///  `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_tag_remove", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_tag_remove(PureEngine* engine, byte* name, byte* kind, byte* value);

        /// <summary>
        ///  Weave the two whole verses `a_ref` / `b_ref` into the weave named `name`
        ///  (created on first use). `added` is a caller-supplied UTC timestamp.
        ///
        ///  # Safety
        ///  `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_weave_add_link", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_weave_add_link(PureEngine* engine, byte* name, byte* a_ref, byte* b_ref, byte* added);

        /// <summary>
        ///  **Approve** the `index`-th suggested weave: promote it into `home/weaves`
        ///  with all links approved (merging into a same-named weave there if present)
        ///  and remove the suggestion. `index` is the ordinal from
        ///  `pure_engine_suggested_weaves_json`. Null on success, else an owned error.
        ///
        ///  # Safety
        ///  `engine` is a valid engine pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_weave_approve", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_weave_approve(PureEngine* engine, uint index);

        /// <summary>
        ///  **Reject** the `index`-th suggested weave: delete its file. `index` is the
        ///  ordinal from `pure_engine_suggested_weaves_json`. Null on success, else an
        ///  owned error.
        ///
        ///  # Safety
        ///  `engine` is a valid engine pointer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_weave_reject", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_weave_reject(PureEngine* engine, uint index);

        /// <summary>
        ///  Replace the running notes document of the thread named `name`. Null on
        ///  success, else an owned error. The thread must already exist.
        ///
        ///  # Safety
        ///  `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_thread_set_notes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_thread_set_notes(PureEngine* engine, byte* name, byte* notes);

        /// <summary>
        ///  Set (or clear, with a null `note`) the note on entry `index` of the thread
        ///  named `name`. Null on success, else an owned error.
        ///
        ///  # Safety
        ///  `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_thread_entry_set_note", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_thread_entry_set_note(PureEngine* engine, byte* name, uint index, byte* note);

        /// <summary>
        ///  Replace the notes document of the weave named `name` (marks it hand-written).
        ///  Null on success, else an owned error. The weave must already exist.
        ///
        ///  # Safety
        ///  `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_weave_set_notes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_weave_set_notes(PureEngine* engine, byte* name, byte* notes);

        /// <summary>
        ///  A verse's 1769 translators' margin notes as JSON, or null when the verse
        ///  has none (or the engine was opened from bytes).
        ///
        ///  # Safety
        ///  `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_verse_notes_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_verse_notes_json(PureEngine* engine, byte* ref_key);

        /// <summary>
        ///  The verse's TSK study cross-references (best-voted first) as JSON, or null
        ///  when the verse has none or the TSK artifact is absent.
        ///
        ///  # Safety
        ///  `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_study_xrefs_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_study_xrefs_json(PureEngine* engine, byte* ref_key);

        /// <summary>
        ///  The full weave library (canonical + suggested) with every link field a
        ///  shell needs for connectors, compare cards, the chord map and the
        ///  constellation. Never null on a live engine (empty library → empty list).
        ///
        ///  # Safety
        ///  `engine` is a live engine (or null → null).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_weaves_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_weaves_json(PureEngine* engine);

        /// <summary>
        ///  The symbolic concept engine's view of a Strong's code: occurrence total,
        ///  testament split, concentrating books, per-book dispersion counts,
        ///  collocates, co-occurrence community, and the leitwort discovery when one
        ///  exists. Null when the code never occurs. Built lazily on first call
        ///  (corpus-wide sweep, ~seconds) and cached.
        ///
        ///  # Safety
        ///  `engine` is a live engine; `code` is null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_concept_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_concept_json(PureEngine* engine, byte* code);

        /// <summary>
        ///  A short English gloss for a Strong's code — the modal KJV rendering across
        ///  its occurrences (≤80 sampled), falling back to a distilled dictionary
        ///  clause. Plain text (not JSON); null when nothing sensible exists.
        ///
        ///  # Safety
        ///  `engine` is a live engine; `code` is null or valid NUL-terminated UTF-8.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_gloss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_gloss(PureEngine* engine, byte* code);

        /// <summary>
        ///  Author a weave link carrying word spans — the Full-study "pin a word in
        ///  each pane, widen, ＋ link" flow. Span bounds are token indices; pass a
        ///  negative bound for a span-less side. Null on success, else an owned error.
        ///
        ///  # Safety
        ///  `engine` is a live engine; string params are null or valid NUL-terminated
        ///  UTF-8 for the call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_engine_weave_add_link_spans", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_engine_weave_add_link_spans(PureEngine* engine, byte* name, byte* a_ref, byte* b_ref, int a_lo, int a_hi, int b_lo, int b_hi, byte* added);

        /// <summary>
        ///  Load the cross-platform shell config (`%APPDATA%\pure-study\config.json` on
        ///  Windows) as JSON: `{studyMode, bodySize, openPanes, activePane, firstRun}`.
        ///  `firstRun` is true only when no config file existed. Never null.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_config_load_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_config_load_json();

        /// <summary>
        ///  Save the shell config from the same JSON shape (unknown fields ignored,
        ///  `firstRun` ignored). Null on success, else an owned error message.
        ///
        ///  # Safety
        ///  `json` is null or valid NUL-terminated UTF-8 for the call.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "pure_config_save_json", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* pure_config_save_json(byte* json);


    }

    /// <summary>
    ///  The loaded, immutable study core: corpus + Strong's dictionary + the search
    ///  and occurrence indices every lookup rides on. Opaque to C; construct with
    ///  [`pure_engine_open`] / [`pure_engine_open_from_bytes`], release with
    ///  [`pure_engine_free`].
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct PureEngine
    {
    }

    /// <summary>
    ///  One laid-out chapter: the positioned display list a shell paints and
    ///  hit-tests. Opaque to C; produced by [`pure_engine_layout_chapter`], released
    ///  with [`pure_layout_free`].
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct PureDisplayList
    {
    }

    /// <summary>
    ///  Layout parameters, all in device pixels — the C-ABI mirror of
    ///  `pure_layout::LayoutConfig` (passed by value, so it is `#[repr(C)]`).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct PureLayoutConfig
    {
        public float width;
        public float line_height;
        public float space_width;
        public float verse_num_gap;
        public float para_indent;
        public float para_spacing;
        /// <summary>
        ///  Nonzero: start every verse on a fresh line (verse-per-line mode).
        /// </summary>
        public uint verse_break;
    }



}
