/* Plumbline C ABI — GENERATED by `cargo run -p plumbline-ffi --features bindgen`. Do not edit by hand. */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Word supplied by the KJV translators (rendered in italics).
#define PLUMBLINE_FLAG_ADDED 1

// The divine name.
#define PLUMBLINE_FLAG_DIVINE 2

// Psalm superscription / title text.
#define PLUMBLINE_FLAG_TITLE 4

// A paragraph mark (¶) precedes this word.
#define PLUMBLINE_FLAG_PARA 8

// Display only: an AKJV re-rendering, set by the overlay on the display list. Never present
// in `kjv.jsonl` (a frozen bitfield), so read it off a display-list item or a panel token
// rather than off stored data.
#define PLUMBLINE_FLAG_RERENDERED 16

// How many verse references an occurrence list returns before it is capped
// (`total` in the JSON stays honest above this).
#define OCCURRENCE_CAP 500

// The wire-JSON contract version. Bump on any **non-additive** change to the payload shapes
// in `wire.rs` (renames/removals/retypes) so typed decoders fail loudly instead of reading
// nulls; purely additive fields do not bump it. Exported to the C header; golden samples are
// pinned in `tests.rs`. Nothing compares it yet — it is a record, not a gate.
#define PLUMBLINE_WIRE_VERSION 2

// One laid-out chapter: the positioned display list a shell paints and
// hit-tests. Opaque to C; produced by [`plumbline_engine_layout_chapter`], released
// with [`plumbline_layout_free`].
typedef struct PlumblineDisplayList PlumblineDisplayList;

// The loaded, immutable study core: corpus + Strong's dictionary + the search
// and occurrence indices every lookup rides on. Opaque to C; construct with
// [`plumbline_engine_open`] / [`plumbline_engine_open_from_bytes`], release with
// [`plumbline_engine_free`].
typedef struct PlumblineEngine PlumblineEngine;

// Layout parameters, all in device pixels — the C-ABI mirror of
// `plumbline_layout::LayoutConfig` (passed by value, so it is `#[repr(C)]`).
typedef struct PlumblineLayoutConfig {
  float width;
  float line_height;
  float space_width;
  float verse_num_gap;
  float para_indent;
  float para_spacing;
  // Nonzero: start every verse on a fresh line (verse-per-line mode).
  uint32_t verse_break;
  // Nonzero: paint the leading verse numbers (the default). Zero lays the chapter out as
  // prose — a layout input rather than something a shell can skip at paint time, because
  // the number's width and its gap belong to the line whether or not anything is drawn.
  uint32_t verse_numbers;
} PlumblineLayoutConfig;

// Advance-width callback: given the caller's context pointer and a
// NUL-terminated UTF-8 run of text, return its width in device pixels in the
// reader's scripture font. The shell backs this with its native text stack so
// the hit regions this crate computes line up exactly with painted glyphs.
//
// Nullable (`Option<fn>`): a null callback makes layout return null.
//
// # Contract — the callback MUST be total
// It must **not** throw or panic across the boundary and should return a **finite,
// non-negative** width. This crate's [`catch_unwind`] firewall only catches *Rust* panics; a
// foreign exception unwinding out of this callback is undefined behaviour. A returned
// `NaN`/negative is clamped to `0.0` here (a degraded but safe layout) rather than corrupting
// line-breaking.
//
// # Contract — the config must describe the font the callback measures with
// Widths are memoized on this side of the ABI (see [`font_identity`]) and nothing in this ABI
// names a typeface, so a shell that changes the font the callback measures with must also
// move `line_height` or `space_width` in the [`PlumblineLayoutConfig`] it passes. A shell
// that derives both by measuring in the current font satisfies this by construction (the
// web's `space_width` is `measure(" ")` through this very callback). A shell that switched
// typeface while holding both bit-identical would be handed the previous typeface's widths: a
// mis-laid-out chapter.
typedef float (*PlumblineMeasureFn)(void *ctx, const char *text);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The Plumbline core version as a caller-freed NUL-terminated UTF-8 string.
// Never null.
char *plumbline_version(void);

// Free a string previously returned by any `plumbline_*` function. Null is a no-op.
//
// # Safety
// `ptr` must be a pointer returned by this library and not already freed.
void plumbline_string_free(char *ptr);

// Open an engine from an overlay-style home directory containing
// `data/kjv.jsonl` and `data/strongs.json`.
//
// Returns null on failure; if `out_err` is non-null it receives a caller-freed
// error message (and is set to null on success).
//
// # Safety
// `home` is a valid NUL-terminated UTF-8 path; `out_err` is null or a writable
// slot for one `*mut c_char`.
struct PlumblineEngine *plumbline_engine_open(const char *home, char **out_err);

// Open a SECOND engine on a named language's text — what a per-pane language rides on: one
// text beside another, without the UI language moving.
//
// The same home, so the reader's own data (threads, tags, weaves, notes) is the same data:
// every text sits at the KJV's verse addresses, so a refKey means one verse in all of them
// and nothing needs mapping. After an authoring write, call
// [`plumbline_engine_load_core_data`] on this handle too, or its study view stays as it was
// when it opened.
//
// Two deliberate differences from [`plumbline_engine_open`]: the language is a parameter, not
// the global the UI language lives in; and there is NO English fallback, because the caller
// asked for one specific text to put beside another and handing back the one already on
// screen would paint English under a pane labelled otherwise. A missing text is an error the
// shell can act on — it is the shell that offers the download.
//
// Returns null on failure (unknown language code, or the text is not on the device);
// `out_err` behaves as in [`plumbline_engine_open`]. Free it with [`plumbline_engine_free`]
// like any other engine.
//
// # Safety
// `home` and `lang` are valid NUL-terminated UTF-8; `out_err` is null or a
// writable slot for one `*mut c_char`.
struct PlumblineEngine *plumbline_engine_open_lang(const char *home,
                                                   const char *lang,
                                                   char **out_err);

// Open an engine from in-memory bytes — for shells that bundle the data as assets: the
// `kjv.jsonl` text and the `strongs.json` object, each as a length-delimited byte buffer
// (need not be NUL-terminated).
//
// Returns null on failure; `out_err` behaves as in [`plumbline_engine_open`].
//
// # Safety
// Each `*_ptr`/`*_len` pair describes a readable buffer of that length (a null
// pointer with length 0 is treated as empty and will error); `out_err` is null
// or a writable slot.
struct PlumblineEngine *plumbline_engine_open_from_bytes(const uint8_t *kjv_ptr,
                                                         size_t kjv_len,
                                                         const uint8_t *strongs_ptr,
                                                         size_t strongs_len,
                                                         char **out_err);

// Release an engine. Null is a no-op.
//
// # Safety
// `engine` must be a pointer from `plumbline_engine_open*` and not already freed.
void plumbline_engine_free(struct PlumblineEngine *engine);

// Table of contents as JSON: `{"books":[{"id","name","chapters"},...]}` in
// canonical order. Chapter counts reflect the loaded corpus and are floored at
// 1 for any book the corpus lacks (the full KJV corpus has all 66 books, so in
// production the counts are exact). Caller-freed; null only on a null engine.
//
// # Safety
// `engine` is a valid engine pointer.
char *plumbline_engine_toc_json(const struct PlumblineEngine *engine);

// Number of chapters the loaded corpus has for `book` (an OSIS id like
// `"John"`). Floored at 1 for a book the corpus lacks (a safe UI range floor);
// 0 only on a null engine.
//
// # Safety
// `engine` is valid; `book` is a valid NUL-terminated UTF-8 string.
uint32_t plumbline_engine_chapter_count(const struct PlumblineEngine *engine, const char *book);

// The highest verse number in `book` chapter `chapter` — how many verses a
// shell may offer for that chapter (the passage-memorize picker's range).
// 0 for a null engine or a chapter the corpus lacks.
//
// # Safety
// `engine` is valid; `book` is a valid NUL-terminated UTF-8 string.
uint32_t plumbline_engine_chapter_verse_count(const struct PlumblineEngine *engine,
                                              const char *book,
                                              uint32_t chapter);

// A single verse as JSON:
// `{"reference","display","body","title","tokens":[...]}`. `reference` is a
// compact key like `"John 3:16"`. Null if the reference is unknown or
// unparseable. Caller-freed.
//
// # Safety
// `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_verse_json(const struct PlumblineEngine *engine, const char *ref_key);

// A single token as JSON: `{"pre","word","post","render","flags","strongs"}`.
// Null if the reference or token index is out of range. Caller-freed.
//
// # Safety
// `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_token_json(const struct PlumblineEngine *engine,
                                  const char *ref_key,
                                  uint32_t token_index);

// Switch the AKJV overlay on or off for this engine. Off by default: the text is the KJV, and
// the overlay is a reading aid the reader opts into.
//
// Affects the READER only — memory cards, Present, copied text and shared links stay the KJV
// whatever this says, or the overlay has quietly become a second translation.
//
// # Safety
// `engine` is a live engine or null.
void plumbline_engine_set_akjv_overlay(const struct PlumblineEngine *engine, bool on);

// Whether this home actually carries a usable overlay — a shell hides the
// toggle when it doesn't, rather than offering a switch that does nothing.
// False until the stage-2 load has run.
//
// # Safety
// `engine` is a live engine or null.
bool plumbline_engine_akjv_available(const struct PlumblineEngine *engine);

// What the AKJV does to one token, as `{"akjv":"you shall","kjv":"thou shalt"}` — the line a
// word study shows under the headword. Null when the token is not re-rendered, or on a bad
// ref. `kjv` is the run's original words, so the reader can always see what was replaced.
//
// # Safety
// `engine` is valid; `ref_key` is null or a valid NUL-terminated UTF-8 string.
char *plumbline_engine_akjv_token_json(const struct PlumblineEngine *engine,
                                       const char *ref_key,
                                       uint32_t token_index);

// Lay out a chapter into a display list, measuring text through `measure`
// (called with `measure_ctx`). Returns an opaque handle to release with
// [`plumbline_layout_free`], or null on a null engine, a null callback, or an
// unknown/out-of-range book+chapter (no such verses). Because the KJV has no
// empty chapters, a null return reliably means "past the end" — a shell can
// page by advancing until it gets null.
//
// # Safety
// `engine` is valid; `book` is a valid NUL-terminated UTF-8 string; `measure`
// is a valid function pointer for the call and `measure_ctx` is whatever it
// expects (it is passed back verbatim).
struct PlumblineDisplayList *plumbline_engine_layout_chapter(const struct PlumblineEngine *engine,
                                                             const char *book,
                                                             uint32_t chapter,
                                                             struct PlumblineLayoutConfig cfg,
                                                             PlumblineMeasureFn measure,
                                                             void *measure_ctx);

// The full display list as JSON (see [`wire`] for the schema): positioned
// items plus the total painted `width`/`height`. Caller-freed; null on a null
// handle.
//
// # Safety
// `dl` is a valid display-list pointer.
char *plumbline_layout_to_json(const struct PlumblineDisplayList *dl);

// Total painted height in device pixels (scrollbar extent). 0 on a null handle.
//
// # Safety
// `dl` is a valid display-list pointer.
float plumbline_layout_height(const struct PlumblineDisplayList *dl);

// The column width the layout targeted. 0 on a null handle.
//
// # Safety
// `dl` is a valid display-list pointer.
float plumbline_layout_width(const struct PlumblineDisplayList *dl);

// Number of placed items in the display list. 0 on a null handle.
//
// # Safety
// `dl` is a valid display-list pointer.
uint32_t plumbline_layout_item_count(const struct PlumblineDisplayList *dl);

// Resolve a point (in the display list's own coordinate space) to the word
// under it. Returns a `Hit` JSON (`{"verse","display","tokenIndex","strongs"}`)
// or null when the point hits a verse number, a gap, or nothing. Caller-freed.
//
// # Safety
// `dl` is a valid display-list pointer.
char *plumbline_layout_hit_test_json(const struct PlumblineDisplayList *dl, float x, float y);

// Release a display list. Null is a no-op.
//
// # Safety
// `dl` must be a pointer from [`plumbline_engine_layout_chapter`] and not already
// freed.
void plumbline_layout_free(struct PlumblineDisplayList *dl);

// A Strong's entry as JSON: `{"code","lemma","xlit","pron","deriv","def",
// "kjv"}` (unknown fields null). Null when the code is absent. Caller-freed.
//
// # Safety
// `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_strongs_json(const struct PlumblineEngine *engine, const char *code);

// The concordance for a Strong's code as JSON: `{"code","total","capped",
// "verses":["Gen 1:1",...]}`. `verses` is capped at [`OCCURRENCE_CAP`] in
// canonical order; `total` is the honest count and `capped` says whether the
// list was truncated. Caller-freed; null on a null engine.
//
// # Safety
// `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_strongs_occurrences_json(const struct PlumblineEngine *engine,
                                                const char *code);

// The rendering lens for a Strong's code: every distinct English rendering of
// it, most frequent first, each with an occurrence count and its (capped)
// verse refs + token spans. `{"code","renderings":[{"rendering","total",
// "capped","refs":[{"verse","display","span":[start,end]}]}]}`. Each `refs`
// list is capped at [`OCCURRENCE_CAP`]; `renderings` is empty for an untagged
// or unknown code. Null only on a null engine. Caller-freed.
//
// # Safety
// `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_renderings_json(const struct PlumblineEngine *engine, const char *code);

// The reverse lens: the Strong's codes a surface English word translates,
// most frequent first. `{"word","codes":[{"code","count"}]}`. Reveals where
// one English word hides a Greek/Hebrew distinction ("love" ← agape and
// phileo); `codes` is empty for an untagged word. Null only on a null engine.
// Caller-freed.
//
// # Safety
// `engine` is valid; `word` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_word_codes_json(const struct PlumblineEngine *engine, const char *word);

// Run a query through the multi-tier search and return a `SearchAnswer` JSON:
// either `{"kind":"goto",...}` (the query was a reference) or
// `{"kind":"hits","how","total","capped","hits":[...]}`. Null when the query is
// blank or the engine is null. Caller-freed.
//
// # Safety
// `engine` is valid; `query` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_search_json(const struct PlumblineEngine *engine, const char *query);

// [`plumbline_engine_search_json`] narrowed to a scope. `scope` is `all` | `ot` | `nt` |
// `book:<osis>` | `chapter:<osis>:<ch>`; anything else (or null) searches everything.
//
// A reference query still answers `goto` whatever the scope — the reader typed an address,
// and a scope chip must not refuse to take them there.
//
// # Safety
// `engine` is valid; `query` is a valid NUL-terminated UTF-8 string; `scope`
// is null or valid NUL-terminated UTF-8.
char *plumbline_engine_search_scoped_json(const struct PlumblineEngine *engine,
                                          const char *query,
                                          const char *scope);

// The loaded threads as JSON: `{"threads":[{name,notes,created,entries:[…]}]}`.
// Caller-freed; null on a null engine.
//
// # Safety
// `engine` is a valid engine pointer.
char *plumbline_engine_threads_json(const struct PlumblineEngine *engine);

// The loaded tags as JSON: `{"tags":[{name,color,created,members:[…]}]}`.
// Caller-freed; null on a null engine.
//
// # Safety
// `engine` is a valid engine pointer.
char *plumbline_engine_tags_json(const struct PlumblineEngine *engine);

// A verse's weave cross-reference partners as JSON:
// `{"verse","partners":[{"verse","display","weave"}]}`. Caller-freed; null on a
// null engine or an unparseable reference.
//
// # Safety
// `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_verse_xrefs_json(const struct PlumblineEngine *engine, const char *ref_key);

// The suggested weaves (proposals under `home/weaves/suggested`) awaiting
// review, as JSON: `{"suggested":[{index,name,kind,notes,links:[…]}]}`. Each
// item's `index` is the ordinal within the suggested subset — the handle the
// approve/reject calls take. Caller-freed; null on a null engine.
//
// # Safety
// `engine` is a valid engine pointer.
char *plumbline_engine_suggested_weaves_json(const struct PlumblineEngine *engine);

// The fused OT↔NT bridge partners of a Strong's code as JSON:
// `{"code","partners":[{code,sources,prior}]}`, ranked by trust prior. The etymology layer
// works from the dictionary alone, so this is available even for a bytes-opened engine
// (external witnesses need a home). Null on a null engine / invalid code.
//
// # Safety
// `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_bridge_partners_json(const struct PlumblineEngine *engine, const char *code);

// The morphology of one token as JSON:
// `{"verse","tokenIndex","code","gloss"}`. Null when no morphology is loaded,
// the reference is unparseable, or that token carries no annotation.
//
// # Safety
// `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_morph_json(const struct PlumblineEngine *engine,
                                  const char *ref_key,
                                  uint32_t token_index);

// Add the whole verse `ref_key` to the thread named `name` (created on first
// use). `note` may be null; `added` is a caller-supplied UTC timestamp.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_thread_add(struct PlumblineEngine *engine,
                                  const char *name,
                                  const char *ref_key,
                                  const char *note,
                                  const char *added);

// Delete the thread named `name` — its file and every entry on it. Matched
// case-insensitively, like `plumbline_engine_thread_add`. A name with no thread is a success.
// Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; `name` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_thread_remove(struct PlumblineEngine *engine, const char *name);

// Add a target to the tag named `name` (created on first use). `kind` is
// `"verse"` (with `value` a ref key) or `"concept"` (with `value` a Strong's
// code). `note` may be null; `added` is a caller-supplied UTC timestamp.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_tag_add(struct PlumblineEngine *engine,
                               const char *name,
                               const char *kind,
                               const char *value,
                               const char *note,
                               const char *added);

// Remove a target (see [`plumbline_engine_tag_add`] for `kind`/`value`) from the tag
// named `name`. A missing target is a no-op; a missing tag is an error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_tag_remove(struct PlumblineEngine *engine,
                                  const char *name,
                                  const char *kind,
                                  const char *value);

// Delete the whole tag named `name` — its file and every member on it. Matched
// case-insensitively, like `plumbline_engine_tag_add`. A name with no tag is a success. Null
// on success, else an owned error string.
//
// # Safety
// `engine` is valid; `name` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_tag_delete(struct PlumblineEngine *engine, const char *name);

// Rename the tag `from` to `to`, keeping its identity. Matched case-insensitively, like the
// other tag calls; a change of case only is a legal rename onto itself.
//
// Refuses a blank new name, and refuses a name another tag already answers to — that is a
// merge, which is destructive and must be asked for by name (`plumbline_engine_tag_merge`)
// rather than fallen into. A `from` that names no tag is a success with nothing done.
//
// Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; `from`/`to` are null or valid NUL-terminated UTF-8.
char *plumbline_engine_tag_rename(struct PlumblineEngine *engine, const char *from, const char *to);

// Set or clear the tag's category — the grouping heading the tag lists file it under. An
// empty (or blank) `category` clears it. A `name` that answers to no tag is a success with
// nothing done, and setting the category a tag already carries writes nothing.
//
// Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; `name`/`category` are null or valid NUL-terminated UTF-8.
char *plumbline_engine_tag_set_category(struct PlumblineEngine *engine,
                                        const char *name,
                                        const char *category);

// Fold the tag `from` into the tag `into`, then delete `from`. Members already in `into` are
// not duplicated, and the survivor's copy of a shared member wins — letting the source
// overwrite would discard a note the reader wrote on the tag they chose to keep.
//
// Destructive: the source tag's file is removed. Refuses a merge of a tag into itself (source
// and destination would be one file, written and then deleted) and refuses an unknown name.
//
// Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; `from`/`into` are null or valid NUL-terminated UTF-8.
char *plumbline_engine_tag_merge(struct PlumblineEngine *engine,
                                 const char *from,
                                 const char *into);

// Weave the two whole verses `a_ref` / `b_ref` into the weave named `name`
// (created on first use). `added` is a caller-supplied UTC timestamp.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_weave_add_link(struct PlumblineEngine *engine,
                                      const char *name,
                                      const char *a_ref,
                                      const char *b_ref,
                                      const char *added);

// Weave a tag's passages into a canon-ordered **chain** of links: the reader tags a topic
// over time, then turns the tag — or a chosen subset of its members — into a weave to read as
// one thread through the canon. Re-running after the tag grows adds only the new edges
// (find-or-create + link dedup).
//
// `refs_json` is null to take every verse member, else a JSON array of refKeys selecting a
// subset (non-members are ignored). `weave_name` is null to reuse the tag's name. Returns
// null on success, else a caller-freed error string.
//
// # Safety
// `engine` is a valid engine from `plumbline_engine_open*`; string params are null
// or valid NUL-terminated UTF-8 for the duration of the call.
char *plumbline_engine_weave_from_tag(struct PlumblineEngine *engine,
                                      const char *tag_name,
                                      const char *refs_json,
                                      const char *weave_name,
                                      const char *added);

// Approve the `index`-th suggested weave: promote it into `home/weaves` with all links
// approved (merging into a same-named weave there if present) and remove the suggestion.
// `index` is the ordinal from `plumbline_engine_suggested_weaves_json`. Null on success, else
// an owned error.
//
// # Safety
// `engine` is a valid engine pointer.
char *plumbline_engine_weave_approve(struct PlumblineEngine *engine, uint32_t index);

// Reject the `index`-th suggested weave: delete its file. `index` is the ordinal from
// `plumbline_engine_suggested_weaves_json`. Null on success, else an owned error.
//
// # Safety
// `engine` is a valid engine pointer.
char *plumbline_engine_weave_reject(struct PlumblineEngine *engine, uint32_t index);

// Delete the `index`-th weave in the library — its file and every link on it. `index` is the
// flat-library ordinal (`plumbline_engine_weaves_json`, the `weave:i` link verb), NOT the
// suggested ordinal `plumbline_engine_weave_reject` takes. It reaches a suggestion too:
// deleting one is the same act as rejecting it. Null on success, else an owned error.
//
// # Safety
// `engine` is a valid engine pointer.
char *plumbline_engine_weave_delete(struct PlumblineEngine *engine, uint32_t index);

// Replace the running notes document of the thread named `name`. Null on
// success, else an owned error. The thread must already exist.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_thread_set_notes(struct PlumblineEngine *engine,
                                        const char *name,
                                        const char *notes);

// Set (or clear, with a null `note`) the note on entry `index` of the thread
// named `name`. Null on success, else an owned error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_thread_entry_set_note(struct PlumblineEngine *engine,
                                             const char *name,
                                             uint32_t index,
                                             const char *note);

// Drop entry `index` from the thread named `name`. Null on success, else an owned error. The
// thread survives its last entry — deleting the thread itself is
// [`plumbline_engine_thread_remove`].
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_thread_entry_remove(struct PlumblineEngine *engine,
                                           const char *name,
                                           uint32_t index);

// Move entry `from` to position `to` in the thread named `name`. Null on success, else an
// owned error. `to` past the end clamps to the last position, so "move the last one down" is
// a no-op rather than an error the shell must special-case — and a no-op does not rewrite the
// file.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_thread_entry_move(struct PlumblineEngine *engine,
                                         const char *name,
                                         uint32_t from,
                                         uint32_t to);

// Replace the notes document of the weave named `name` (marks it hand-written).
// Null on success, else an owned error. The weave must already exist.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_weave_set_notes(struct PlumblineEngine *engine,
                                       const char *name,
                                       const char *notes);

// A verse's 1769 translators' margin notes as JSON, or null when the verse
// has none (or the engine was opened from bytes).
//
// # Safety
// `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_verse_notes_json(const struct PlumblineEngine *engine, const char *ref_key);

// The verse's TSK study cross-references (best-voted first) as JSON, or null
// when the verse has none or the TSK artifact is absent.
//
// # Safety
// `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_study_xrefs_json(const struct PlumblineEngine *engine, const char *ref_key);

// The full weave library (canonical + suggested) with every link field a
// shell needs for connectors, compare cards, the chord map and the
// constellation. Never null on a live engine (empty library → empty list).
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_weaves_json(const struct PlumblineEngine *engine);

// Every weave link as a deduped canonical verse pair, each endpoint located (ref key +
// book/chapter/verse) and flagged `resolved` when both ends are in the corpus — the one
// derivation behind the connector lines and the chord map, so a shell neither dedupes nor
// parses ref keys itself. Never null on a live engine (empty library → empty list).
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_link_pairs_json(const struct PlumblineEngine *engine);

// The canon overview segmentation: the 8 sections as `(label, first, last)` book indices over
// the 66 books, plus the OT/NT divide (39). Static data frozen in `core::reference`, served
// here so no shell re-hardcodes the bands. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null); the payload does not depend on engine state,
// but the arg keeps the call shape uniform.
char *plumbline_engine_canon_segments_json(const struct PlumblineEngine *engine);

// The hymnal's table of contents, in book-number order:
// `{"hymns":[{id,number,titles,firstLines,tune,meter}]}` — `titles` and
// `firstLines` map language code → string for every language the hymn ships
// in. Empty `hymns` when the home carries no `data/hymnal.json` (an old pack);
// null only on a null engine. Caller-freed.
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_hymnal_json(const struct PlumblineEngine *engine);

// One hymn by id, its chords transposed by `transpose` semitones and split
// into painted `parts` (chord? + text) per line. `transposedKey` is what a
// transpose control displays; chords are spelled for the key they LAND in.
// `transpose` is folded into one octave (-11..=11 effective). Null for an
// unknown id. Caller-freed.
//
// # Safety
// `engine` is a live engine; `id` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_hymn_json(const struct PlumblineEngine *engine,
                                 const char *id,
                                 int32_t transpose);

// The book-to-book weave chord map: canon-ordered book-pair counts over the deduped link
// pairs (`{pairs:[{a,b,count}], max, otNtDivide, bookCount}`), where `a`/`b` are book indices
// (`a <= b`), so a shell lays out ribbons without folding pairs or deriving the max. Never
// null on a live engine (empty library → empty pairs, max 1).
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_chord_map_json(const struct PlumblineEngine *engine);

// One laid-out page of the constellation (the weave-library overview popup): lanes with nodes
// + edges as fractions, plus the pin/paging state resolved into a caption. The shell holds
// the transient `page` and `pins` (weave indices, the handles the lanes carry) and passes
// them in; everything derived — usable filter, largest-first order, per-verse degree, jitter,
// lane assignment, paging — lives here. `pins_json` is a JSON array of weave indices (e.g.
// `"[3,7]"`); null / empty / malformed means no pins. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null); `pins_json` is null or valid
// NUL-terminated UTF-8.
char *plumbline_engine_constellation_json(const struct PlumblineEngine *engine,
                                          uint32_t page,
                                          const char *pins_json);

// The symbolic concept engine's view of a Strong's code: occurrence total,
// testament split, concentrating books, per-book dispersion counts,
// collocates, co-occurrence community, and the leitwort discovery when one
// exists. Null when the code never occurs. Built lazily on first call
// (corpus-wide sweep, ~seconds) and cached.
//
// # Safety
// `engine` is a live engine; `code` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_concept_json(const struct PlumblineEngine *engine, const char *code);

// A short English gloss for a Strong's code — the modal KJV rendering across
// its occurrences (≤80 sampled), falling back to a distilled dictionary
// clause. Plain text (not JSON); null when nothing sensible exists.
//
// # Safety
// `engine` is a live engine; `code` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_gloss(const struct PlumblineEngine *engine, const char *code);

// A panel view as the typed block list (`{blocks:[…]}`). Word study: the clicked
// word's dictionary + Full-study tiers + this verse's cross-references/notes.
// `full` gates the R&D tiers + author actions. Never null on a live engine.
//
// # Safety
// `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_word_study_blocks_json(const struct PlumblineEngine *engine,
                                              const char *ref_key,
                                              uint32_t token_index,
                                              bool full);

// [`plumbline_engine_word_study_blocks_json`] with per-tier gates instead of the Simple/Full
// flag: `gates` bit 0 = curated-scholarship (human) analysis, bit 1 = learned/statistical
// (machine) analysis. The text and the reader's own data are always on.
//
// # Safety
// `engine` is a live engine; `ref_key` is a valid NUL-terminated UTF-8 string.
char *plumbline_engine_word_study_blocks2_json(const struct PlumblineEngine *engine,
                                               const char *ref_key,
                                               uint32_t token_index,
                                               uint32_t gates);

// The standalone `code:CODE[:word]` study card (the reverse rendering-lens
// target). `word` may be null. Never null on a live engine.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_code_study_blocks_json(const struct PlumblineEngine *engine,
                                              const char *code,
                                              const char *word,
                                              bool full);

// [`plumbline_engine_code_study_blocks_json`] with per-tier gates (bit 0 = human
// analysis, bit 1 = machine analysis).
//
// # Safety
// `engine` is a live engine; `code` is valid NUL-terminated UTF-8; `word` is
// null or valid NUL-terminated UTF-8.
char *plumbline_engine_code_study_blocks2_json(const struct PlumblineEngine *engine,
                                               const char *code,
                                               const char *word,
                                               uint32_t gates);

// The full concordance for a code as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine; `code` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_concordance_blocks_json(const struct PlumblineEngine *engine,
                                               const char *code);

// The concordance filtered to one rendering of a code, as blocks. Never null
// on a live engine.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_rendering_concordance_blocks_json(const struct PlumblineEngine *engine,
                                                         const char *code,
                                                         const char *rendering);

// The threads list as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_threads_blocks_json(const struct PlumblineEngine *engine);

// One thread's detail as blocks (out-of-range index → the threads list). Never
// null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_thread_blocks_json(const struct PlumblineEngine *engine, uint32_t index);

// The tags list as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_tags_blocks_json(const struct PlumblineEngine *engine);

// One tag's detail as blocks (out-of-range index → the tags list). Never null
// on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_tag_blocks_json(const struct PlumblineEngine *engine, uint32_t index);

// The weaves list as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_weaves_blocks_json(const struct PlumblineEngine *engine);

// The suggested-weave review queue as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_suggested_blocks_json(const struct PlumblineEngine *engine);

// A weave compare card as blocks (out-of-range index → empty). `full` adds the
// edit-notes action. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_compare_blocks_json(const struct PlumblineEngine *engine,
                                           uint32_t index,
                                           bool full);

// Search results as blocks (goto link or ranked hits with snippets). Null when
// the query is blank or the engine is null.
//
// # Safety
// `engine` is a live engine; `query` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_search_blocks_json(const struct PlumblineEngine *engine, const char *query);

// [`plumbline_engine_search_blocks_json`] narrowed to a scope token — see
// [`plumbline_engine_search_scoped_json`] for the vocabulary.
//
// # Safety
// `engine` is a live engine; `query` and `scope` are null or valid
// NUL-terminated UTF-8.
char *plumbline_engine_search_blocks_scoped_json(const struct PlumblineEngine *engine,
                                                 const char *query,
                                                 const char *scope);

// Author a weave link carrying word spans. Span bounds are token indices; pass a negative
// bound for a span-less side. Null on success, else an owned error.
//
// # Safety
// `engine` is a live engine; string params are null or valid NUL-terminated
// UTF-8 for the call.
char *plumbline_engine_weave_add_link_spans(struct PlumblineEngine *engine,
                                            const char *name,
                                            const char *a_ref,
                                            const char *b_ref,
                                            int32_t a_lo,
                                            int32_t a_hi,
                                            int32_t b_lo,
                                            int32_t b_hi,
                                            const char *added);

// Parse a panel link URI into the typed verb the shell dispatches on (`{verb, …}`; see
// `plumbline_core::panel::parse_link`) — the one verb vocabulary, so a shell routes clicks
// through the core instead of re-splitting the URI and drifting from what the panel emits.
// Engine-independent. Null for an unknown verb or malformed payload.
//
// # Safety
// `uri` is null or valid NUL-terminated UTF-8 for the call.
char *plumbline_route_link_json(const char *uri);

// Load the shell config as JSON: `{studyMode, bodySize, openPanes, activePane, firstRun}`.
// `firstRun` is true only when no config file existed. Never null.
char *plumbline_config_load_json(void);

// Save the shell config from the same JSON shape (unknown fields ignored,
// `firstRun` ignored). Null on success, else an owned error message.
//
// # Safety
// `json` is null or valid NUL-terminated UTF-8 for the call.
char *plumbline_config_save_json(const char *json);

// Clipboard text for a verse (or its chapter, for the `chapter*` kinds) in one of the shapes
// `plumbline_core::export::CopyKind` names (`verse` / `verseRef` / `verseMarkdown` /
// `chapter` / `chapterMarkdown`). Plain text, not JSON; null on a bad ref, an unknown kind,
// or a verse the corpus lacks. Caller-freed.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated
// UTF-8 for the call.
char *plumbline_engine_copy_text(const struct PlumblineEngine *engine,
                                 const char *ref_key,
                                 const char *kind);

// The reader's personal note on a verse as JSON (`{verse,display,text,created,
// updated}`), or null when the verse has no note (or the engine has no home).
//
// # Safety
// `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_user_note_json(const struct PlumblineEngine *engine, const char *ref_key);

// All the reader's personal notes as JSON (`{notes:[…]}`), in canonical reading order. Never
// null on a live engine (no notes → empty list).
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_user_notes_json(const struct PlumblineEngine *engine);

// Set (or clear, with an empty `text`) the reader's personal note on a verse,
// atomically, then reload. `stamp` is a caller-supplied UTC timestamp. Null on
// success, else an owned error string.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated
// UTF-8 for the call.
char *plumbline_engine_user_note_set(struct PlumblineEngine *engine,
                                     const char *ref_key,
                                     const char *text,
                                     const char *stamp);

// The colour palette for a theme (`light`/`dark`/`night`; unknown → light) as
// JSON — every semantic role as a `#rrggbb` hex. Engine-independent. Never null.
//
// # Safety
// `theme` is null or valid NUL-terminated UTF-8 for the call.
char *plumbline_theme_palette_json(const char *theme);

// Which seating a local date and hour fall in — `"sunday-morning"`, `"sunday-evening"`,
// `"wednesday-evening"` or `"other"`. Engine-independent, never null.
//
// The caller passes its own local date (`YYYY-MM-DD`) and hour (0–23), because the core has
// no clock and no timezone: a slot computed in UTC would put a Sunday-evening service in
// Monday for half the world. The rule lives here so no shell reimplements it.
//
// # Safety
// `date` is null or valid NUL-terminated UTF-8 for the call.
char *plumbline_session_slot(const char *date, uint32_t hour);

// [`plumbline_session_slot`] to the minute, honouring a configured Sunday
// service time. `minute` is minutes since local midnight (0–1439);
// `sunday_service` is the config's `sundayService` value, or **-1 when the
// reader never set one**, which keeps the before-noon rule. With a time set,
// `"sunday-morning"` runs from the service start until 1.5 hours after it —
// see `core::session_slot::slot_for_at`. Engine-independent, never null.
//
// # Safety
// `date` is null or valid NUL-terminated UTF-8 for the call.
char *plumbline_session_slot_at(const char *date, uint32_t minute, int32_t sunday_service);

// Every user-visible string, for one language, in ONE call:
// `{"lang","strings":{id: text, …},"languages":[{"code","endonym"}]}`.
//
// The whole catalogue at once, deliberately: a shell asks at startup and holds the map, where
// a call per string would be thousands of round trips across the wasm boundary to render one
// screen.
//
// Takes both the reader's setting and the device's locale and resolves them here rather than
// in each shell — an empty setting means "follow the device" (`Config::language`). Either may
// be null. Both tolerate a region tag (`de-CH` gets German) and anything unrecognised falls
// through to English, so an unsupported locale gets a working app rather than an error; the
// reply's `lang` says which one won. Strings absent from the resolved language fall back to
// English key by key.
//
// `languages` rides along because a language picker needs the list, each labelled in itself.
//
// Engine-independent: a shell needs its chrome before an engine exists. Never null.
//
// # Safety
// `chosen` and `device` are null or valid NUL-terminated UTF-8 for the call.
char *plumbline_i18n_catalog_json(const char *chosen, const char *device);

// Set the language the ENGINE writes in, and answer with the code it resolved.
//
// Call once, at startup, alongside `plumbline_i18n_catalog_json`. The catalogue covers what a
// shell spells; this covers what the core spells — every book name and reference it hands
// back, in the table of contents, search hits, weave endpoints, note headers, thread entries,
// the reading map.
//
// Two calls rather than one on purpose: resolving a language and choosing one are different
// acts, and a getter with a global side effect would mean every test that asked for a
// catalogue repainted the whole process.
//
// Same arguments and rule as the catalogue call: an empty or unknown `chosen` falls through
// to `device`, and an unknown device is English. Caller-freed; never null.
//
// # Safety
// `chosen` and `device` are null or valid NUL-terminated UTF-8 for the call.
char *plumbline_i18n_set_language(const char *chosen, const char *device);

// Force the lazy analytics indexes (concept engine, leitwort scan) to build now — call once
// on a background thread at startup in Full mode so the first study click doesn't stall. Safe
// from any thread (the builds are `OnceLock`-guarded) and idempotent. Null on success, else
// an owned error.
//
// # Safety
// `engine` is a live engine (or null → an error string).
char *plumbline_engine_warm_indexes(const struct PlumblineEngine *engine);

// Load the stage-2 core data (Strong's dictionary + a study reload for the 1769 margin notes)
// once those files have arrived in the home — the web boots on the corpus alone and calls
// this when the rest of the core pack lands. Idempotent, cheap when nothing is missing. Null
// on success, else an owned error.
//
// # Safety
// `engine` is a live engine (or null → an error string).
char *plumbline_engine_load_core_data(const struct PlumblineEngine *engine);

// Load the optional R&D artifact (the morphology sidecar) from the engine's home if it was
// absent at open — the web fetches the R&D pack in the background, writes it into the home,
// then calls this. Idempotent, cheap when the file is still missing, safe from any thread.
// Null on success, else an owned error.
//
// # Safety
// `engine` is a live engine (or null → an error string).
char *plumbline_engine_load_rnd_data(const struct PlumblineEngine *engine);

// Grade the verse `verse_ref` at `now` (RFC3339 UTC), creating its SRS card on
// first review; SM-2 reschedules and appends to the review log. `grade` is one
// of `again` / `hard` / `good` / `easy`. Null on success, else an owned error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_memory_grade(struct PlumblineEngine *engine,
                                    const char *verse_ref,
                                    const char *grade,
                                    const char *now);

// Start memorizing `verse_ref` — seed its SRS card (due now) if it isn't
// already one; no review is logged. `now` is a caller-supplied UTC timestamp.
// Null on success, else an owned error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_memory_add(struct PlumblineEngine *engine,
                                  const char *verse_ref,
                                  const char *now);

// Start memorizing the passage `start_ref`…`through_ref` (inclusive) as ONE card, keyed and
// listed by `start_ref`.
//
// `through_ref` must name a later verse of the same chapter; anything else seeds a plain
// single-verse card. Already memorizing `start_ref` is a no-op, so re-running with a
// different end does NOT re-span the card — remove it first. Null on success, else an owned
// error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_memory_add_passage(struct PlumblineEngine *engine,
                                          const char *start_ref,
                                          const char *through_ref,
                                          const char *now);

// Stop memorizing `verse_ref` (remove its card); a missing card is a no-op.
// Null on success, else an owned error.
//
// # Safety
// `engine` is valid; `verse_ref` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_memory_remove(struct PlumblineEngine *engine, const char *verse_ref);

// The verse's SRS card as JSON (schedule + mastery + review log), or null if
// the verse isn't being memorized (or the engine has no home).
//
// # Safety
// `engine` is a live engine; `verse_ref` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_memory_card_json(const struct PlumblineEngine *engine,
                                        const char *verse_ref);

// Verses due for review at `now` (RFC3339), in reading order, as `{refs:[...]}`. Never null
// on a live engine (empty when nothing is due).
//
// # Safety
// `engine` is a live engine; `now` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_memory_due_json(const struct PlumblineEngine *engine, const char *now);

// The coverage-map data at `now`: per-verse standing (mastery + recency) plus
// the 8-section rollup, as `{verses:[...],sections:[...]}`.
//
// # Safety
// `engine` is a live engine; `now` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_memory_coverage_json(const struct PlumblineEngine *engine, const char *now);

// The activity heatmap as `{days:[{day,reviews}]}` — reviews per calendar day,
// oldest first, from every card's review log. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *plumbline_engine_memory_activity_json(const struct PlumblineEngine *engine);

// A drill prompt for `verse_ref` at blank-out `level` (0 = full text … max):
// the text, its first-letter skeleton, and the blanked form. When `verse_ref`
// is a passage card's first verse, the drill covers the whole passage. Null if
// the verse isn't found.
//
// # Safety
// `engine` is a live engine; `verse_ref` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_memory_drill_json(const struct PlumblineEngine *engine,
                                         const char *verse_ref,
                                         uint32_t level);

// Score a typed recall of `verse_ref` against the verse text — `{accuracy,
// words:[{word,ok}]}`, LCS-aligned. Null if the verse isn't found.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_memory_score_json(const struct PlumblineEngine *engine,
                                         const char *verse_ref,
                                         const char *typed);

// The in-app guide as panel blocks. Engine-independent (static content). Never
// null.
char *plumbline_panel_guide_blocks_json(void);

// The About card as panel blocks. Engine-independent (static content). Never
// null.
char *plumbline_panel_about_blocks_json(void);

// Every running devotional with its open day, plus the catalogue every picker
// offers, as `{running:[…], catalogue:[…]}`. Never null on a live engine.
//
// `lang` selects the text (falling back to English per entry); null reads as
// English. `today` is the reader's local `YYYY-MM-DD`; null reads as "no day",
// leaving every open entry `available` — a missing date must not lock a reader
// out.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_devotionals_json(const struct PlumblineEngine *engine,
                                        const char *lang,
                                        const char *today);

// One day of a booklet, whether or not it is the open one — what the reader's
// page paints when they browse back to day 3. Null for a day the booklet does
// not have, or an unknown id.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_devotional_day_json(const struct PlumblineEngine *engine,
                                           const char *id,
                                           uint32_t day,
                                           const char *lang);

// Start a devotional by its catalogue `id`. Starting one already running is a
// no-op, not a re-seed, so Start from a stale list cannot wipe progress; a
// reader may run two booklets at once. Null on success, else an owned error
// string.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_devotional_start(struct PlumblineEngine *engine,
                                        const char *id,
                                        const char *now);

// Stop a devotional, removing its run file and its progress. An absent run is a
// no-op, not an error. Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; `id` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_devotional_stop(struct PlumblineEngine *engine, const char *id);

// Bank day `day` of a running devotional on the reader's local `today`
// (`YYYY-MM-DD`) — the Done at the foot of the page, and the only signal that a
// day was read. Re-banking a banked day is a no-op that does not re-stamp the
// date, so a double tap cannot push tomorrow's entry further away. Null on
// success, else an owned error string.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_devotional_done(struct PlumblineEngine *engine,
                                       const char *id,
                                       uint32_t day,
                                       const char *today);

// Pause or resume a devotional: its file and banked days stay put, and it stops
// asking (no chip) while `paused`. An absent id is an error — pausing one that
// is not running means the shell's list is stale, and saying so beats a silent
// no-op. Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; `id` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_devotional_set_paused(struct PlumblineEngine *engine,
                                             const char *id,
                                             bool paused);

// The reading map's tuning as JSON: `{wordsPerMinute, completeAt, freshDays,
// staleDays, graceSeconds, tickSeconds, idleSeconds}`. Engine-independent and
// free, unlike the same object riding on `reading_books_json`. Never null.
char *plumbline_reading_spec_json(void);

// One sample of reading time.
//
// `book`/`chapter` are what is on screen; a NULL `book` means nothing is being
// read right now (a dialog is up, the app is going to the background, the
// reader left the chapter) and banks the tail. `reached` is the deepest verse
// of that chapter the reader has scrolled to, `step_seconds` the seconds this
// sample covers (a shell passes its own sample interval; the core clamps it),
// and `interacted` whether anything was touched since the last sample.
//
// Most calls answer null. When the core decides the banked seconds are worth
// writing down it records them and answers the same
// `{book,chapter,pct,completed,lastRead?}` `reading_record_json` does, so a
// shell reacts to `completed` in exactly one place.
//
// Null also when the engine has no home to write to — reading is simply not
// tracked then.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_reading_tick_json(struct PlumblineEngine *engine,
                                         const char *book,
                                         uint32_t chapter,
                                         uint32_t reached,
                                         float step_seconds,
                                         bool interacted,
                                         const char *now);

// Every running plan with derived state, plus the builtin catalogue for the
// picker, as `{running:[…], builtins:[…]}`. Never null on a live engine.
// `now` is what dates each schedule's `doneToday`; null reads as "no day",
// so the flag is simply false everywhere.
//
// # Safety
// `engine` is a live engine; `now` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_plans_json(const struct PlumblineEngine *engine, const char *now);

// Start a built-in schedule plan by its `id` (see `plumbline_engine_plans_json`
// `builtins`). Starting a plan whose class is already occupied replaces the
// running one — the shell confirms first — and passing an already-running id
// re-seeds it from scratch. Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_plan_start(struct PlumblineEngine *engine, const char *id, const char *now);

// Start (or resume) a concept study for `tag`, returning the run's plan id —
// what the shell writes into `config.conceptStudy` to enter the mode. The id is
// derived from the tag (`run-<slug>`), so re-starting a concept already being
// swept resumes it with coverage intact rather than forking a second run. The
// tag itself need not exist yet; the first tap-to-tag creates it.
//
// Returns the id on success, or an error string prefixed with `!` (which no
// plan id can start with) so the one out-parameter carries both.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_concept_study_start(struct PlumblineEngine *engine,
                                           const char *tag,
                                           const char *now);

// Mark a chapter swept in a concept study (generous: no dwell, any order), and
// persist. A non-concept-study id, or a chapter already swept, is a harmless no-op.
// Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_concept_study_sweep(struct PlumblineEngine *engine,
                                           const char *id,
                                           const char *book,
                                           uint32_t chapter);

// Stop a plan — remove its file. Ending a concept study leaves its tag and every
// verse gathered untouched (the point of the sweep). An absent id is a no-op.
// Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; `id` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_plan_stop(struct PlumblineEngine *engine, const char *id);

// Pause or resume a plan: its file, progress and class stay put, and shells
// stop asking for its today (no chip, no card) while `paused`. A concept study
// can pause too. An absent id is an error — pausing a plan that is not running
// means the shell's list is stale, and saying so beats a silent no-op. Null on
// success, else an owned error string.
//
// # Safety
// `engine` is valid; `id` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_plan_set_paused(struct PlumblineEngine *engine, const char *id, bool paused);

// Every book's reading standing at `now` (RFC3339), canon order, as
// `{books:[…],since,spec}`. Never null on a live engine.
//
// # Safety
// `engine` is a live engine; `now` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_reading_books_json(const struct PlumblineEngine *engine, const char *now);

// One book's chapters at `now`, chapter order, as `{book,chapters:[…],since,spec}`.
// Null for an unknown book id.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_reading_chapters_json(const struct PlumblineEngine *engine,
                                             const char *book,
                                             const char *now);

// Credit reading time to a chapter and persist it.
//
// `reached` is the furthest verse number the reader has had on screen and `seconds` the dwell
// since the last call, reported on the cadence in `spec.tickSeconds` plus on leaving the chapter
// and on going to the background.
//
// Returns the resulting `{book,chapter,pct,completed,lastRead?}`, or null when
// the engine has no home to write to (reading is simply not tracked then).
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_reading_record_json(struct PlumblineEngine *engine,
                                           const char *book,
                                           uint32_t chapter,
                                           uint32_t reached,
                                           float seconds,
                                           const char *now);

// Log a chapter as read on `date` (`YYYY-MM-DD`, or any RFC3339 stamp — only
// the day is kept) — the by-hand affordance for reading done in a paper Bible.
// Full credit. Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *plumbline_engine_reading_mark_read(struct PlumblineEngine *engine,
                                         const char *book,
                                         uint32_t chapter,
                                         const char *date);

// Drop a chapter's reading record — the way back out of a date set by mistake;
// the chapter returns to unread. Null on success, else an owned error string.
//
// # Safety
// `engine` is valid; `book` is null or valid NUL-terminated UTF-8.
char *plumbline_engine_reading_forget(struct PlumblineEngine *engine,
                                      const char *book,
                                      uint32_t chapter);

// Build the link this reader hands over, from `{base?, church?,
// startAsNewBeliever?, at?}` (all optional — `{}` is the plain app link).
//
// Answers `{url, base, church, hasChurch, title, siteUrl}`: the link for the QR
// and the share sheet, the church as the core normalized it, and the label /
// site a Church button needs. Query encoding and church cleaning live here, not
// in each shell.
//
// Null only when `request` is null or not JSON.
//
// # Safety
// `request` is null or valid NUL-terminated UTF-8 for the call.
char *plumbline_share_url_json(const char *request);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
