/* pure-study C ABI — GENERATED by `cargo run -p pure-ffi --features bindgen`. Do not edit by hand. */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Word supplied by the KJV translators (rendered in italics).
#define PURE_FLAG_ADDED 1

// The divine name.
#define PURE_FLAG_DIVINE 2

// Psalm superscription / title text.
#define PURE_FLAG_TITLE 4

// A paragraph mark (¶) precedes this word.
#define PURE_FLAG_PARA 8

// How many verse references an occurrence list returns before it is capped
// (`total` in the JSON stays honest above this).
#define OCCURRENCE_CAP 500

// The wire-JSON contract version. Bump on any **non-additive** change to the
// payload shapes in `wire.rs` (renames/removals/retypes) so typed decoders
// can fail loudly instead of silently reading nulls; purely additive fields
// do not bump it. Exported to the C header; golden samples are pinned in
// `tests.rs`.
#define PURE_WIRE_VERSION 1

// One laid-out chapter: the positioned display list a shell paints and
// hit-tests. Opaque to C; produced by [`pure_engine_layout_chapter`], released
// with [`pure_layout_free`].
typedef struct PureDisplayList PureDisplayList;

// The loaded, immutable study core: corpus + Strong's dictionary + the search
// and occurrence indices every lookup rides on. Opaque to C; construct with
// [`pure_engine_open`] / [`pure_engine_open_from_bytes`], release with
// [`pure_engine_free`].
typedef struct PureEngine PureEngine;

// Layout parameters, all in device pixels — the C-ABI mirror of
// `pure_layout::LayoutConfig` (passed by value, so it is `#[repr(C)]`).
typedef struct PureLayoutConfig {
  float width;
  float line_height;
  float space_width;
  float verse_num_gap;
  float para_indent;
  float para_spacing;
  // Nonzero: start every verse on a fresh line (verse-per-line mode).
  uint32_t verse_break;
} PureLayoutConfig;

// Advance-width callback: given the caller's context pointer and a
// NUL-terminated UTF-8 run of text, return its width in device pixels in the
// reader's scripture font. The shell backs this with its native text stack so
// the hit regions this crate computes line up exactly with painted glyphs.
//
// Nullable (`Option<fn>`): a null callback makes layout return null.
//
// # Contract — the callback MUST be total
// It must **not** throw or panic across the boundary and should return a
// **finite, non-negative** width. This crate's [`catch_unwind`] firewall only
// catches *Rust* panics; a foreign exception unwinding out of this callback is
// undefined behaviour — on .NET it fast-fails the process, on JNA it is
// swallowed and reported as `0.0`. A returned `NaN`/negative is clamped to
// `0.0` here (a degraded but safe layout) rather than corrupting line-breaking.
typedef float (*PureMeasureFn)(void *ctx, const char *text);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The pure-study core version as a caller-freed NUL-terminated UTF-8 string.
// Never null.
char *pure_study_version(void);

// Free a string previously returned by any `pure_*` function. Null is a no-op.
//
// # Safety
// `ptr` must be a pointer returned by this library and not already freed.
void pure_study_string_free(char *ptr);

// Open an engine from an overlay-style home directory containing
// `data/kjv.jsonl` and `data/strongs.json`.
//
// Returns null on failure; if `out_err` is non-null it receives a caller-freed
// error message (and is set to null on success).
//
// # Safety
// `home` is a valid NUL-terminated UTF-8 path; `out_err` is null or a writable
// slot for one `*mut c_char`.
struct PureEngine *pure_engine_open(const char *home, char **out_err);

// Open an engine from in-memory bytes — for shells that bundle the data as
// assets/resources (decision #3): the `kjv.jsonl` text and the `strongs.json`
// object, each as a length-delimited byte buffer (need not be NUL-terminated).
//
// Returns null on failure; `out_err` behaves as in [`pure_engine_open`].
//
// # Safety
// Each `*_ptr`/`*_len` pair describes a readable buffer of that length (a null
// pointer with length 0 is treated as empty and will error); `out_err` is null
// or a writable slot.
struct PureEngine *pure_engine_open_from_bytes(const uint8_t *kjv_ptr,
                                               size_t kjv_len,
                                               const uint8_t *strongs_ptr,
                                               size_t strongs_len,
                                               char **out_err);

// Release an engine. Null is a no-op.
//
// # Safety
// `engine` must be a pointer from `pure_engine_open*` and not already freed.
void pure_engine_free(struct PureEngine *engine);

// Table of contents as JSON: `{"books":[{"id","name","chapters"},...]}` in
// canonical order. Chapter counts reflect the loaded corpus and are floored at
// 1 for any book the corpus lacks (the full KJV corpus has all 66 books, so in
// production the counts are exact). Caller-freed; null only on a null engine.
//
// # Safety
// `engine` is a valid engine pointer.
char *pure_engine_toc_json(const struct PureEngine *engine);

// Number of chapters the loaded corpus has for `book` (an OSIS id like
// `"John"`). Floored at 1 for a book the corpus lacks (a safe UI range floor);
// 0 only on a null engine.
//
// # Safety
// `engine` is valid; `book` is a valid NUL-terminated UTF-8 string.
uint32_t pure_engine_chapter_count(const struct PureEngine *engine, const char *book);

// A single verse as JSON:
// `{"reference","display","body","title","tokens":[...]}`. `reference` is a
// compact key like `"John 3:16"`. Null if the reference is unknown or
// unparseable. Caller-freed.
//
// # Safety
// `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
char *pure_engine_verse_json(const struct PureEngine *engine, const char *ref_key);

// A single token as JSON: `{"pre","word","post","render","flags","strongs"}`.
// Null if the reference or token index is out of range. Caller-freed.
//
// # Safety
// `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
char *pure_engine_token_json(const struct PureEngine *engine,
                             const char *ref_key,
                             uint32_t token_index);

// Lay out a chapter into a display list, measuring text through `measure`
// (called with `measure_ctx`). Returns an opaque handle to release with
// [`pure_layout_free`], or null on a null engine, a null callback, or an
// unknown/out-of-range book+chapter (no such verses). Because the KJV has no
// empty chapters, a null return reliably means "past the end" — a shell can
// page by advancing until it gets null.
//
// # Safety
// `engine` is valid; `book` is a valid NUL-terminated UTF-8 string; `measure`
// is a valid function pointer for the call and `measure_ctx` is whatever it
// expects (it is passed back verbatim).
struct PureDisplayList *pure_engine_layout_chapter(const struct PureEngine *engine,
                                                   const char *book,
                                                   uint32_t chapter,
                                                   struct PureLayoutConfig cfg,
                                                   PureMeasureFn measure,
                                                   void *measure_ctx);

// The full display list as JSON (see [`wire`] for the schema): positioned
// items plus the total painted `width`/`height`. Caller-freed; null on a null
// handle.
//
// # Safety
// `dl` is a valid display-list pointer.
char *pure_layout_to_json(const struct PureDisplayList *dl);

// Total painted height in device pixels (scrollbar extent). 0 on a null handle.
//
// # Safety
// `dl` is a valid display-list pointer.
float pure_layout_height(const struct PureDisplayList *dl);

// The column width the layout targeted. 0 on a null handle.
//
// # Safety
// `dl` is a valid display-list pointer.
float pure_layout_width(const struct PureDisplayList *dl);

// Number of placed items in the display list. 0 on a null handle.
//
// # Safety
// `dl` is a valid display-list pointer.
uint32_t pure_layout_item_count(const struct PureDisplayList *dl);

// Resolve a point (in the display list's own coordinate space) to the word
// under it. Returns a `Hit` JSON (`{"verse","display","tokenIndex","strongs"}`)
// or null when the point hits a verse number, a gap, or nothing. Caller-freed.
//
// # Safety
// `dl` is a valid display-list pointer.
char *pure_layout_hit_test_json(const struct PureDisplayList *dl, float x, float y);

// Release a display list. Null is a no-op.
//
// # Safety
// `dl` must be a pointer from [`pure_engine_layout_chapter`] and not already
// freed.
void pure_layout_free(struct PureDisplayList *dl);

// A Strong's entry as JSON: `{"code","lemma","xlit","pron","deriv","def",
// "kjv"}` (unknown fields null). Null when the code is absent. Caller-freed.
//
// # Safety
// `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
char *pure_engine_strongs_json(const struct PureEngine *engine, const char *code);

// The concordance for a Strong's code as JSON: `{"code","total","capped",
// "verses":["Gen 1:1",...]}`. `verses` is capped at [`OCCURRENCE_CAP`] in
// canonical order; `total` is the honest count and `capped` says whether the
// list was truncated. Caller-freed; null on a null engine.
//
// # Safety
// `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
char *pure_engine_strongs_occurrences_json(const struct PureEngine *engine, const char *code);

// The rendering lens for a Strong's code: every distinct English rendering of
// it, most frequent first, each with an occurrence count and its (capped)
// verse refs + token spans. `{"code","renderings":[{"rendering","total",
// "capped","refs":[{"verse","display","span":[start,end]}]}]}`. Each `refs`
// list is capped at [`OCCURRENCE_CAP`]; `renderings` is empty for an untagged
// or unknown code. Null only on a null engine. Caller-freed.
//
// # Safety
// `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
char *pure_engine_renderings_json(const struct PureEngine *engine, const char *code);

// The reverse lens: the Strong's codes a surface English word translates,
// most frequent first. `{"word","codes":[{"code","count"}]}`. Reveals where
// one English word hides a Greek/Hebrew distinction ("love" ← agape and
// phileo); `codes` is empty for an untagged word. Null only on a null engine.
// Caller-freed.
//
// # Safety
// `engine` is valid; `word` is a valid NUL-terminated UTF-8 string.
char *pure_engine_word_codes_json(const struct PureEngine *engine, const char *word);

// Run a query through the multi-tier search and return a `SearchAnswer` JSON:
// either `{"kind":"goto",...}` (the query was a reference) or
// `{"kind":"hits","how","total","capped","hits":[...]}`. Null when the query is
// blank or the engine is null. Caller-freed.
//
// # Safety
// `engine` is valid; `query` is a valid NUL-terminated UTF-8 string.
char *pure_engine_search_json(const struct PureEngine *engine, const char *query);

// The loaded threads as JSON: `{"threads":[{name,notes,created,entries:[…]}]}`.
// Caller-freed; null on a null engine.
//
// # Safety
// `engine` is a valid engine pointer.
char *pure_engine_threads_json(const struct PureEngine *engine);

// The loaded tags as JSON: `{"tags":[{name,color,created,members:[…]}]}`.
// Caller-freed; null on a null engine.
//
// # Safety
// `engine` is a valid engine pointer.
char *pure_engine_tags_json(const struct PureEngine *engine);

// A verse's weave cross-reference partners as JSON:
// `{"verse","partners":[{"verse","display","weave"}]}`. Caller-freed; null on a
// null engine or an unparseable reference.
//
// # Safety
// `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
char *pure_engine_verse_xrefs_json(const struct PureEngine *engine, const char *ref_key);

// The suggested weaves (proposals under `home/weaves/suggested`) awaiting
// review, as JSON: `{"suggested":[{index,name,kind,notes,links:[…]}]}`. Each
// item's `index` is the ordinal within the suggested subset — the handle the
// approve/reject calls take. Caller-freed; null on a null engine.
//
// # Safety
// `engine` is a valid engine pointer.
char *pure_engine_suggested_weaves_json(const struct PureEngine *engine);

// Concept neighbours of a Strong's code as JSON:
// `{"code","near":[{code,score}],"cross":[{code,score}]}` (same-testament, then
// cross-testament — the latter empty unless the embedding is aligned). Null
// when no embedding is loaded or the args are invalid.
//
// # Safety
// `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
char *pure_engine_concept_neighbours_json(const struct PureEngine *engine,
                                          const char *code,
                                          uint32_t k);

// The fused OT↔NT bridge partners of a Strong's code as JSON:
// `{"code","partners":[{code,sources,prior}]}`, ranked by trust prior. The
// etymology layer works from the dictionary alone, so this is available even
// for a bytes-opened engine (external witnesses need a home). Null on a null
// engine / invalid code.
//
// # Safety
// `engine` is valid; `code` is a valid NUL-terminated UTF-8 string.
char *pure_engine_bridge_partners_json(const struct PureEngine *engine, const char *code);

// The morphology of one token as JSON:
// `{"verse","tokenIndex","code","gloss"}`. Null when no morphology is loaded,
// the reference is unparseable, or that token carries no annotation.
//
// # Safety
// `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
char *pure_engine_morph_json(const struct PureEngine *engine,
                             const char *ref_key,
                             uint32_t token_index);

// "Verses like this one" (SIF) as JSON:
// `{"verse","in":[{verse,display,score}],"cross":[…]}`. The SIF model is built
// lazily on the first call (heavy) and cached. Null when no embedding is
// loaded or the reference is unparseable.
//
// # Safety
// `engine` is valid; `ref_key` is a valid NUL-terminated UTF-8 string.
char *pure_engine_similar_verses_json(const struct PureEngine *engine,
                                      const char *ref_key,
                                      uint32_t k);

// Add the whole verse `ref_key` to the thread named `name` (created on first
// use). `note` may be null; `added` is a caller-supplied UTC timestamp.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_thread_add(struct PureEngine *engine,
                             const char *name,
                             const char *ref_key,
                             const char *note,
                             const char *added);

// Add a target to the tag named `name` (created on first use). `kind` is
// `"verse"` (with `value` a ref key) or `"concept"` (with `value` a Strong's
// code). `note` may be null; `added` is a caller-supplied UTC timestamp.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_tag_add(struct PureEngine *engine,
                          const char *name,
                          const char *kind,
                          const char *value,
                          const char *note,
                          const char *added);

// Remove a target (see [`pure_engine_tag_add`] for `kind`/`value`) from the tag
// named `name`. A missing target is a no-op; a missing tag is an error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_tag_remove(struct PureEngine *engine,
                             const char *name,
                             const char *kind,
                             const char *value);

// Weave the two whole verses `a_ref` / `b_ref` into the weave named `name`
// (created on first use). `added` is a caller-supplied UTC timestamp.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_weave_add_link(struct PureEngine *engine,
                                 const char *name,
                                 const char *a_ref,
                                 const char *b_ref,
                                 const char *added);

// Weave a tag's passages into a canon-ordered **chain** of links — the
// accumulate-then-organize flow: the reader tags a topic over time (e.g.
// "Rapture"), then turns the tag — or a chosen subset of its members — into a
// weave to read as one thread through the canon. Re-running after the tag
// grows just adds the new edges (find-or-create + link dedup).
//
// `refs_json` is null to take every verse member, else a JSON array of
// refKeys selecting a subset (non-members are ignored). `weave_name` is null
// to reuse the tag's name. Returns null on success, else a caller-freed
// error string.
//
// # Safety
// `engine` is a valid engine from `pure_engine_open*`; string params are null
// or valid NUL-terminated UTF-8 for the duration of the call.
char *pure_engine_weave_from_tag(struct PureEngine *engine,
                                 const char *tag_name,
                                 const char *refs_json,
                                 const char *weave_name,
                                 const char *added);

// **Approve** the `index`-th suggested weave: promote it into `home/weaves`
// with all links approved (merging into a same-named weave there if present)
// and remove the suggestion. `index` is the ordinal from
// `pure_engine_suggested_weaves_json`. Null on success, else an owned error.
//
// # Safety
// `engine` is a valid engine pointer.
char *pure_engine_weave_approve(struct PureEngine *engine, uint32_t index);

// **Reject** the `index`-th suggested weave: delete its file. `index` is the
// ordinal from `pure_engine_suggested_weaves_json`. Null on success, else an
// owned error.
//
// # Safety
// `engine` is a valid engine pointer.
char *pure_engine_weave_reject(struct PureEngine *engine, uint32_t index);

// Replace the running notes document of the thread named `name`. Null on
// success, else an owned error. The thread must already exist.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_thread_set_notes(struct PureEngine *engine, const char *name, const char *notes);

// Set (or clear, with a null `note`) the note on entry `index` of the thread
// named `name`. Null on success, else an owned error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_thread_entry_set_note(struct PureEngine *engine,
                                        const char *name,
                                        uint32_t index,
                                        const char *note);

// Replace the notes document of the weave named `name` (marks it hand-written).
// Null on success, else an owned error. The weave must already exist.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_weave_set_notes(struct PureEngine *engine, const char *name, const char *notes);

// A verse's 1769 translators' margin notes as JSON, or null when the verse
// has none (or the engine was opened from bytes).
//
// # Safety
// `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
char *pure_engine_verse_notes_json(const struct PureEngine *engine, const char *ref_key);

// The verse's TSK study cross-references (best-voted first) as JSON, or null
// when the verse has none or the TSK artifact is absent.
//
// # Safety
// `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
char *pure_engine_study_xrefs_json(const struct PureEngine *engine, const char *ref_key);

// The full weave library (canonical + suggested) with every link field a
// shell needs for connectors, compare cards, the chord map and the
// constellation. Never null on a live engine (empty library → empty list).
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_weaves_json(const struct PureEngine *engine);

// Every weave link as a deduped canonical verse pair, each endpoint located
// (ref key + book/chapter/verse) and flagged `resolved` when both ends are in
// the corpus. The one derivation behind the ambient connector lines and the
// chord map, so a shell neither dedupes nor parses ref keys itself. Never null
// on a live engine (empty library → empty list).
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_link_pairs_json(const struct PureEngine *engine);

// The canon overview segmentation: the 8 sections as `(label, first, last)`
// book indices over the 66 books, plus the OT/NT divide (39). Static data
// frozen in `core::reference` — served here so a non-Rust shell consumes the
// one source instead of re-hardcoding the bands. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null); the payload does not depend on
// engine state, but the arg keeps the call shape uniform.
char *pure_engine_canon_segments_json(const struct PureEngine *engine);

// The book-to-book weave chord map: canon-ordered book-pair counts over the
// deduped link pairs (`{pairs:[{a,b,count}], max, otNtDivide, bookCount}`),
// where `a`/`b` are book indices (`a <= b`). The one fold behind the "Weave
// map" popup, so a shell lays out ribbons without folding pairs or deriving the
// max. Never null on a live engine (empty library → empty pairs, max 1).
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_chord_map_json(const struct PureEngine *engine);

// One laid-out page of the constellation (the weave-library overview popup):
// lanes with nodes + edges as **fractions**, plus the pin/paging state already
// resolved into a caption. The shell holds the transient `page` and `pins`
// (weave indices, the same handles the lanes carry) and passes them in;
// everything derived — usable filter, largest-first order, per-verse degree,
// jitter, lane assignment, paging — lives here. `pins_json` is a JSON array of
// weave indices (e.g. `"[3,7]"`); null / empty / malformed means no pins.
// Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null); `pins_json` is null or valid
// NUL-terminated UTF-8.
char *pure_engine_constellation_json(const struct PureEngine *engine,
                                     uint32_t page,
                                     const char *pins_json);

// The symbolic concept engine's view of a Strong's code: occurrence total,
// testament split, concentrating books, per-book dispersion counts,
// collocates, co-occurrence community, and the leitwort discovery when one
// exists. Null when the code never occurs. Built lazily on first call
// (corpus-wide sweep, ~seconds) and cached.
//
// # Safety
// `engine` is a live engine; `code` is null or valid NUL-terminated UTF-8.
char *pure_engine_concept_json(const struct PureEngine *engine, const char *code);

// The concept map for a code: the radial neighbourhood (embedding neighbours ∪
// collocation community, deduped, labels pre-baked) plus the per-book
// dispersion counts in canon order. One call replaces the shell's spoke
// assembly and its four separate lookups (neighbours / concept / gloss /
// lemma). Never null on a live engine + valid code — a code with no stats
// still yields its centre label and any embedding spokes (empty dispersion).
//
// # Safety
// `engine` is a live engine; `code` is null or valid NUL-terminated UTF-8.
char *pure_engine_concept_map_json(const struct PureEngine *engine, const char *code);

// A short English gloss for a Strong's code — the modal KJV rendering across
// its occurrences (≤80 sampled), falling back to a distilled dictionary
// clause. Plain text (not JSON); null when nothing sensible exists.
//
// # Safety
// `engine` is a live engine; `code` is null or valid NUL-terminated UTF-8.
char *pure_engine_gloss(const struct PureEngine *engine, const char *code);

// A panel view as the typed block list (`{blocks:[…]}`). Word study: the clicked
// word's dictionary + Full-study tiers + this verse's cross-references/notes.
// `full` gates the R&D tiers + author actions. Never null on a live engine.
//
// # Safety
// `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
char *pure_engine_word_study_blocks_json(const struct PureEngine *engine,
                                         const char *ref_key,
                                         uint32_t token_index,
                                         bool full);

// [`pure_engine_word_study_blocks_json`] with per-tier gates instead of the
// legacy Simple/Full flag: `gates` bit 0 = curated-scholarship (human)
// analysis, bit 1 = learned/statistical (machine) analysis. The text and the
// reader's own data are always on.
//
// # Safety
// `engine` is a live engine; `ref_key` is a valid NUL-terminated UTF-8 string.
char *pure_engine_word_study_blocks2_json(const struct PureEngine *engine,
                                          const char *ref_key,
                                          uint32_t token_index,
                                          uint32_t gates);

// The standalone `code:CODE[:word]` study card (the reverse rendering-lens
// target). `word` may be null. Never null on a live engine.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_code_study_blocks_json(const struct PureEngine *engine,
                                         const char *code,
                                         const char *word,
                                         bool full);

// [`pure_engine_code_study_blocks_json`] with per-tier gates (bit 0 = human
// analysis, bit 1 = machine analysis).
//
// # Safety
// `engine` is a live engine; `code` is valid NUL-terminated UTF-8; `word` is
// null or valid NUL-terminated UTF-8.
char *pure_engine_code_study_blocks2_json(const struct PureEngine *engine,
                                          const char *code,
                                          const char *word,
                                          uint32_t gates);

// The full concordance for a code as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine; `code` is null or valid NUL-terminated UTF-8.
char *pure_engine_concordance_blocks_json(const struct PureEngine *engine, const char *code);

// The concordance filtered to one rendering of a code, as blocks. Never null
// on a live engine.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_rendering_concordance_blocks_json(const struct PureEngine *engine,
                                                    const char *code,
                                                    const char *rendering);

// The threads list as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_threads_blocks_json(const struct PureEngine *engine);

// One thread's detail as blocks (out-of-range index → the threads list). Never
// null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_thread_blocks_json(const struct PureEngine *engine, uint32_t index);

// The tags list as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_tags_blocks_json(const struct PureEngine *engine);

// One tag's detail as blocks (out-of-range index → the tags list). Never null
// on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_tag_blocks_json(const struct PureEngine *engine, uint32_t index);

// The weaves list as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_weaves_blocks_json(const struct PureEngine *engine);

// The suggested-weave review queue as blocks. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_suggested_blocks_json(const struct PureEngine *engine);

// A weave compare card as blocks (out-of-range index → empty). `full` adds the
// edit-notes action. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_compare_blocks_json(const struct PureEngine *engine, uint32_t index, bool full);

// Search results as blocks (goto link or ranked hits with snippets). Null when
// the query is blank or the engine is null.
//
// # Safety
// `engine` is a live engine; `query` is null or valid NUL-terminated UTF-8.
char *pure_engine_search_blocks_json(const struct PureEngine *engine, const char *query);

// Author a weave link carrying word spans — the Full-study "pin a word in
// each pane, widen, ＋ link" flow. Span bounds are token indices; pass a
// negative bound for a span-less side. Null on success, else an owned error.
//
// # Safety
// `engine` is a live engine; string params are null or valid NUL-terminated
// UTF-8 for the call.
char *pure_engine_weave_add_link_spans(struct PureEngine *engine,
                                       const char *name,
                                       const char *a_ref,
                                       const char *b_ref,
                                       int32_t a_lo,
                                       int32_t a_hi,
                                       int32_t b_lo,
                                       int32_t b_hi,
                                       const char *added);

// Parse a panel link URI into the typed verb the shell dispatches on
// (`{verb, …}`; see `pure_core::panel::parse_link`) — the one verb vocabulary,
// so a non-Rust shell routes clicks through the core instead of re-splitting
// the URI string and risking drift from what the panel emits. Engine-
// independent. Null for an unknown verb or malformed payload (a shell then
// ignores the click).
//
// # Safety
// `uri` is null or valid NUL-terminated UTF-8 for the call.
char *pure_route_link_json(const char *uri);

// Load the cross-platform shell config (`%APPDATA%\pure-study\config.json` on
// Windows) as JSON: `{studyMode, bodySize, openPanes, activePane, firstRun}`.
// `firstRun` is true only when no config file existed. Never null.
char *pure_config_load_json(void);

// Save the shell config from the same JSON shape (unknown fields ignored,
// `firstRun` ignored). Null on success, else an owned error message.
//
// # Safety
// `json` is null or valid NUL-terminated UTF-8 for the call.
char *pure_config_save_json(const char *json);

// Clipboard text for a verse (or its chapter, for the `chapter*` kinds) in one
// of the shapes `pure_core::export::CopyKind` names (`verse` / `verseRef` /
// `verseMarkdown` / `chapter` / `chapterMarkdown`). Plain text, not JSON; null
// on a bad ref, an unknown kind, or a verse the corpus lacks. Caller-freed.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated
// UTF-8 for the call.
char *pure_engine_copy_text(const struct PureEngine *engine, const char *ref_key, const char *kind);

// The reader's personal note on a verse as JSON (`{verse,display,text,created,
// updated}`), or null when the verse has no note (or the engine has no home).
//
// # Safety
// `engine` is a live engine; `ref_key` is null or valid NUL-terminated UTF-8.
char *pure_engine_user_note_json(const struct PureEngine *engine, const char *ref_key);

// All the reader's personal notes as JSON (`{notes:[…]}`), in canonical reading
// order — for the gutter marks and a "your notes" browser. Never null on a live
// engine (no notes → empty list).
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_user_notes_json(const struct PureEngine *engine);

// Set (or clear, with an empty `text`) the reader's personal note on a verse,
// atomically, then reload. `stamp` is a caller-supplied UTC timestamp. Null on
// success, else an owned error string.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated
// UTF-8 for the call.
char *pure_engine_user_note_set(struct PureEngine *engine,
                                const char *ref_key,
                                const char *text,
                                const char *stamp);

// Set (or clear, with a null `color`) the swatch colour of the tag named
// `name`, then reload. Drives highlighting (a colour-bearing tag washes its
// verses). Null on success, else an owned error.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated
// UTF-8 for the call.
char *pure_engine_tag_set_color(struct PureEngine *engine, const char *name, const char *color);

// Add a word-precise highlight range to the tag named `name` (created on first
// use, taking `color` as its tone). The range runs from `start_ref`+`start_tok`
// to `end_ref`+`end_tok` (inclusive token indices under `kjv1769-tok2`);
// endpoints are ordered canonically here, so a backwards drag is fine. `color`
// may be null (the range then inherits the tag's colour). `added` is a
// caller-supplied UTC timestamp. Null on success, else an owned error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_highlight_add(struct PureEngine *engine,
                                const char *name,
                                const char *color,
                                const char *start_ref,
                                uint32_t start_tok,
                                const char *end_ref,
                                uint32_t end_tok,
                                const char *added);

// Remove the highlight range with these endpoints from the tag named `name`.
// Endpoints are ordered canonically to match how they were stored. A missing
// range is a no-op; a missing tag is an error. Null on success, else an error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_highlight_remove(struct PureEngine *engine,
                                   const char *name,
                                   const char *start_ref,
                                   uint32_t start_tok,
                                   const char *end_ref,
                                   uint32_t end_tok);

// Drop every highlight range covering `verse_ref` from all tags, then reload —
// the drag-remove path (a whole range goes even if only one of its verses was
// targeted). Null on success, else an owned error.
//
// # Safety
// `engine` is valid; `verse_ref` is null or valid NUL-terminated UTF-8.
char *pure_engine_highlight_clear_verse(struct PureEngine *engine, const char *verse_ref);

// The highlight washes for a chapter as JSON (`{book,chapter,verses:[{verse,
// color}]}`): each verse that belongs to a colour-bearing tag, with the tone
// the shell washes behind it. Never null on a live engine (none → empty list).
//
// # Safety
// `engine` is a live engine; `book` is null or valid NUL-terminated UTF-8.
char *pure_engine_chapter_highlights_json(const struct PureEngine *engine,
                                          const char *book,
                                          uint32_t chapter);

// The colour palette for a theme (`light`/`dark`/`night`; unknown → light) as
// JSON — every semantic role as a `#rrggbb` hex. Engine-independent. Never null.
//
// # Safety
// `theme` is null or valid NUL-terminated UTF-8 for the call.
char *pure_theme_palette_json(const char *theme);

// The fixed highlight tones (`{tones:[{name,hex}]}`) — the shell's swatch menu.
// Engine-independent. Never null.
char *pure_theme_highlight_tones_json(void);

// Force the lazy analytics indexes (concept engine, leitwort scan, SIF verse
// similarity) to build now — call once on a background thread at startup in
// Full mode so the first study click doesn't stall. Safe to call from any
// thread (the builds are `OnceLock`-guarded) and idempotent. Null on success,
// else an owned error.
//
// # Safety
// `engine` is a live engine (or null → an error string).
char *pure_engine_warm_indexes(const struct PureEngine *engine);

// Grade the verse `verse_ref` at `now` (RFC3339 UTC), creating its SRS card on
// first review; SM-2 reschedules and appends to the review log. `grade` is one
// of `again` / `hard` / `good` / `easy`. Null on success, else an owned error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_memory_grade(struct PureEngine *engine,
                               const char *verse_ref,
                               const char *grade,
                               const char *now);

// Start memorizing `verse_ref` — seed its SRS card (due now) if it isn't
// already one; no review is logged. `now` is a caller-supplied UTC timestamp.
// Null on success, else an owned error.
//
// # Safety
// `engine` is valid; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_memory_add(struct PureEngine *engine, const char *verse_ref, const char *now);

// Stop memorizing `verse_ref` (remove its card); a missing card is a no-op.
// Null on success, else an owned error.
//
// # Safety
// `engine` is valid; `verse_ref` is null or valid NUL-terminated UTF-8.
char *pure_engine_memory_remove(struct PureEngine *engine, const char *verse_ref);

// The verse's SRS card as JSON (schedule + mastery + review log), or null if
// the verse isn't being memorized (or the engine has no home).
//
// # Safety
// `engine` is a live engine; `verse_ref` is null or valid NUL-terminated UTF-8.
char *pure_engine_memory_card_json(const struct PureEngine *engine, const char *verse_ref);

// Verses due for review at `now` (RFC3339), reading order — the study queue, as
// `{refs:[...]}`. Never null on a live engine (empty when nothing is due).
//
// # Safety
// `engine` is a live engine; `now` is null or valid NUL-terminated UTF-8.
char *pure_engine_memory_due_json(const struct PureEngine *engine, const char *now);

// The coverage-map data at `now`: per-verse standing (mastery + recency) plus
// the 8-section rollup, as `{verses:[...],sections:[...]}`.
//
// # Safety
// `engine` is a live engine; `now` is null or valid NUL-terminated UTF-8.
char *pure_engine_memory_coverage_json(const struct PureEngine *engine, const char *now);

// The activity heatmap as `{days:[{day,reviews}]}` — reviews per calendar day,
// oldest first, from every card's review log. Never null on a live engine.
//
// # Safety
// `engine` is a live engine (or null → null).
char *pure_engine_memory_activity_json(const struct PureEngine *engine);

// A drill prompt for `verse_ref` at blank-out `level` (0 = full text … max):
// the verse text, its first-letter skeleton, and the blanked form. Null if the
// verse isn't found.
//
// # Safety
// `engine` is a live engine; `verse_ref` is null or valid NUL-terminated UTF-8.
char *pure_engine_memory_drill_json(const struct PureEngine *engine,
                                    const char *verse_ref,
                                    uint32_t level);

// Score a typed recall of `verse_ref` against the verse text — `{accuracy,
// words:[{word,ok}]}`, LCS-aligned. Null if the verse isn't found.
//
// # Safety
// `engine` is a live engine; the string args are null or valid NUL-terminated UTF-8.
char *pure_engine_memory_score_json(const struct PureEngine *engine,
                                    const char *verse_ref,
                                    const char *typed);

// The in-app guide as panel blocks. Engine-independent (static content). Never
// null.
char *pure_panel_guide_blocks_json(void);

// The About card as panel blocks. Engine-independent (static content). Never
// null.
char *pure_panel_about_blocks_json(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
