// GENERATED by scripts/gen-i18n.mjs from crates/core/src/i18n/*.json — do not edit.
//
// The boot.* keys only: what the splash and the boot-failure screen say,
// which is everything the shell must be able to paint before the engine exists.
// The rest of the catalogue arrives on the boot reply.

export const BOOT_STRINGS: Record<string, Record<string, string>> = {
  de: {
    "boot.couldNotOpen": "Der Korpus konnte nicht geöffnet werden",
    "boot.details": "Technische Details",
    "boot.dismiss": "Ausblenden",
    "boot.error.corpus": "Plumbline konnte die Bibeldaten auf diesem Gerät nicht lesen. Beim Neuladen wird nachgeladen, was fehlt.",
    "boot.error.engine": "Die Studien-Engine wurde beendet, bevor Plumbline fertig geöffnet war. Beim Neuladen startet sie erneut.",
    "boot.error.network": "Plumbline konnte nicht vollständig herunterladen, was zum Öffnen nötig ist. Verbindung prüfen und erneut versuchen. Einmal auf dem Gerät geladen, öffnet es ganz ohne Verbindung.",
    "boot.error.quota": "Auf diesem Gerät ist kein Platz mehr, um die Bibel zu speichern.",
    "boot.error.stale": "Diese Version von Plumbline ist älter als die gerade geladenen Bibeldaten. Die Seite neu laden, um die aktuelle Version zu holen.",
    "boot.error.storage": "Dieser Browser lässt Plumbline nichts auf dem Gerät speichern. Website-Daten (Cookies und Speicher) müssen für diese Adresse erlaubt sein. Auch ein privates Fenster kann das blockieren.",
    "boot.error.unknown": "Plumbline konnte nicht starten. Neuladen behebt das meistens; falls nicht, sind die Details unten das, was ein Fehlerbericht braucht.",
    "boot.error.wasm": "Die Engine von Plumbline ließ sich in diesem Browser nicht starten. Andere Tabs schließen und neu laden ist einen Versuch wert; tritt es weiter auf, ist der Browser vielleicht zu alt für WebAssembly.",
    "boot.mishap": "Etwas ist schiefgelaufen — neu laden",
    "boot.oneTime": "3 MB Download",
    "boot.phase.download": "Bibeldaten werden geladen — {percent} %",
    "boot.phase.open": "Der Text wird geöffnet…",
    "boot.phase.prepare": "Die Studien-Engine wird vorbereitet…",
    "boot.phase.warm": "Die Analysen werden aufgebaut…",
    "boot.reload": "Neu laden",
    "boot.retry": "Erneut versuchen",
    "boot.startupFailed": "Start fehlgeschlagen: {why}",
    "boot.tagline": "Die Heilige Schrift"
  },
  en: {
    "boot.couldNotOpen": "could not open corpus",
    "boot.details": "Technical details",
    "boot.dismiss": "Dismiss",
    "boot.error.corpus": "Plumbline could not read the scripture data on this device. Reloading re-downloads what is missing.",
    "boot.error.engine": "The study engine stopped before Plumbline finished opening. Reloading starts it again.",
    "boot.error.network": "Plumbline could not finish downloading what it needs to open. Check the connection and try again. Once it is on the device it opens with no connection at all.",
    "boot.error.quota": "There is no room left on this device to store the Bible.",
    "boot.error.stale": "This copy of Plumbline is older than the scripture data it just downloaded. Reload the page to pick up the current version.",
    "boot.error.storage": "This browser is not letting Plumbline store anything on the device. Site data (cookies and storage) has to be allowed for this address. A private window may block it too.",
    "boot.error.unknown": "Plumbline could not start. Reloading usually clears it; if it does not, the details below are what a bug report needs.",
    "boot.error.wasm": "Plumbline's engine would not start in this browser. Closing other tabs and reloading is worth trying; if it keeps happening, the browser may be too old for WebAssembly.",
    "boot.mishap": "Something went wrong — reload",
    "boot.oneTime": "3 MB download",
    "boot.phase.download": "Fetching scripture data — {percent}%",
    "boot.phase.open": "Opening the text…",
    "boot.phase.prepare": "Preparing the study engine…",
    "boot.phase.warm": "Building the analytics…",
    "boot.reload": "Reload",
    "boot.retry": "Retry",
    "boot.startupFailed": "Startup failed: {why}",
    "boot.tagline": "The Holy Bible"
  },
};
